### ISSUE TITLE
Unmarshal exception Android Studio

### ISSUE THREAD

**Issue by atozchannel** [jpmml/jpmml-evaluator#100]
I have successfully integrated pmml-evaluator and it worked on Eclipse. However, in Android, there are many libraries missing and I downloaded and imported all of them, except for one that I couldn't add due to the "DexBuilder: Failed to process... .jar" exception. I'm having this exception when trying to unmarshal the pmml file (pmml = unmarshal(is);). Is there any work around so that I can convert the pmml file to a PMML object?

**Comment by vruusmann** [comment]
Android is missing JAXB support. Therefore, you cannot use the `JAXBUtil#unmarshal(..)` method for reading the PMML class model object from the PMML file.

Please switch to the [JPMML-Evaluator-Android](https://github.com/jpmml/jpmml-android) library.

**Comment by atozchannel** [comment]
Thanks a lot (y) :D
