### ISSUE TITLE
Java heap issues when marshialling huge PMMLs

### ISSUE THREAD

**Issue by dhakerHach** [jpmml/jpmml-evaluator#104]
Hello 
Are there any solutions to  parse huge PMML files greater than 100mo without changing the memory allocation for java jre.
are there other loading mode ; for instance a file buffering or partial parsing.
My goal is to extract only the dictionary fields, outputs, algorithm, model name and the version of the xsd.
Your help is greatly appreciated.
kind Regards.

**Comment by vruusmann** [comment]
> Are there any solutions to parse huge PMML files greater than 100mo without changing the memory allocation for java.

Just as a matter of perspective, 100 MB is a size of a typical decision tree ensemble model (random forest, gbdt, etc). A desktop computer should be able to read it into memory in one second or so.

Anyway, on to your question. If you wish to selectively skip PMML content, then you need to introduce appropriate SAX filters into JAXB input source. Specifically, see the `org.jpmml.model.filters.ElementFilter` filter class that belongs to the JPMML-Model library: https://github.com/jpmml/jpmml-model/blob/master/pmml-model/src/main/java/org/jpmml/model/filters/ElementFilter.java

Identify which PMML element(s) are the proflem for you (when dealing with decision tree ensemble models, then it would be the `Node` element), and then skip it like that:
```Java
InputStream is = ...;
Source source = JAXBUtil.createFilteredSource(new InputSource(is), new ElementFilter("Node"));
PMML pmml = JAXBUtil.unmarshalPMML(source);
```
