### ISSUE TITLE
Outputting `TreeModel` and `RuleSetModel` confidence estimates

### ISSUE THREAD

**Issue by infiton** [jpmml/jpmml-evaluator#106]
hey there, I'm looking into an example from the 4.3 spec at http://dmg.org/pmml/v4-3/TreeModel.html and have modified the PMML there to output the probabilities:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3">
  <Header copyright="www.dmg.org" description="A very small tree model to demonstrate missing value handling and confidence calculation."/>
  <DataDictionary numberOfFields="4">
    <DataField name="temperature" optype="continuous" dataType="double"/>
    <DataField name="humidity" optype="continuous" dataType="double"/>
    <DataField name="outlook" optype="categorical" dataType="string">
      <Value value="sunny"/>
      <Value value="overcast"/>
      <Value value="rain"/>
    </DataField>
    <DataField name="whatIdo" optype="categorical" dataType="string">
      <Value value="will play"/>
      <Value value="may play"/>
      <Value value="no play"/>
    </DataField>
  </DataDictionary>
  <TreeModel modelName="golfing" functionName="classification" missingValueStrategy="defaultChild" missingValuePenalty="0.8">
    <MiningSchema>
      <MiningField name="temperature"/>
      <MiningField name="humidity"/>
      <MiningField name="outlook"/>
      <MiningField name="whatIdo" usageType="target"/>
    </MiningSchema>
    <Output>
      <OutputField name="predicted_whatIdo" feature="predictedValue" dataType="string"/>
      <OutputField name="confidence_will_play" value="will play" feature="confidence" optype="continuous" dataType="double"/>
      <OutputField name="confidence_may_play" value="may play" feature="confidence" optype="continuous" dataType="double"/>
      <OutputField name="confidence_no_play" value="no play" feature="confidence" optype="continuous" dataType="double"/>
    </Output>
    <Node id="1" score="will play" recordCount="100" defaultChild="2">
      <True/>
      <ScoreDistribution value="will play" recordCount="60" confidence="0.6"/>
      <ScoreDistribution value="may play" recordCount="30" confidence="0.3"/>
      <ScoreDistribution value="no play" recordCount="10" confidence="0.1"/>
      <Node id="2" score="will play" recordCount="50" defaultChild="3">
        <SimplePredicate field="outlook" operator="equal" value="sunny"/>
        <ScoreDistribution value="will play" recordCount="40" confidence="0.8"/>
        <ScoreDistribution value="may play" recordCount="2" confidence="0.04"/>
        <ScoreDistribution value="no play" recordCount="8" confidence="0.16"/>
        <Node id="3" score="will play" recordCount="40">
          <CompoundPredicate booleanOperator="surrogate">
            <SimplePredicate field="temperature" operator="greaterOrEqual" value="50"/>
            <SimplePredicate field="humidity" operator="lessThan" value="80"/>
          </CompoundPredicate>
          <ScoreDistribution value="will play" recordCount="36" confidence="0.9"/>
          <ScoreDistribution value="may play" recordCount="2" confidence="0.05"/>
          <ScoreDistribution value="no play" recordCount="2" confidence="0.05"/>
        </Node>
        <Node id="4" score="no play" recordCount="10">
          <CompoundPredicate booleanOperator="surrogate">
            <SimplePredicate field="temperature" operator="lessThan" value="50"/>
            <SimplePredicate field="humidity" operator="greaterOrEqual" value="80"/>
          </CompoundPredicate>
          <ScoreDistribution value="will play" recordCount="4" confidence="0.4"/>
          <ScoreDistribution value="may play" recordCount="0" confidence="0.0"/>
          <ScoreDistribution value="no play" recordCount="6" confidence="0.6"/>
        </Node>
      </Node>
      <Node id="5" score="may play" recordCount="50">
        <CompoundPredicate booleanOperator="or">
          <SimplePredicate field="outlook" operator="equal" value="overcast"/>
          <SimplePredicate field="outlook" operator="equal" value="rain"/>
        </CompoundPredicate>
        <ScoreDistribution value="will play" recordCount="20" confidence="0.4"/>
        <ScoreDistribution value="may play" recordCount="28" confidence="0.56"/>
        <ScoreDistribution value="no play" recordCount="2" confidence="0.04"/>
      </Node>
    </Node>
  </TreeModel>
</PMML>
```

I'm confused with the scoring the describe in example 4:

>Example 4 - Scoring with defaultChild missing value handling
Suppose we alter the example TreeModel to set the missingValueStrategy attribute to defaultChild. We also add the attribute missingValuePenalty and set it to 0.8.
>
>Now consider how to score a case with temperature=40, humidity=70, but outlook is unknown.
>
>The predicate of node 2 evaluates to UNKNOWN, due to missing value for outlook, so missingValueHandlingStrategy defaultChild is invoked at this point. Scoring continues by selecting node 1's defaultChild (node 2). Scoring then continues normally from node 2, the prediction returned is "no play", but the confidence returned is 0.6 multiplied by the missingValuePenalty of 0.8, which is 0.48.

When I score this using JPMML I get the normalized probabilities (0.6, 0.0 and 0.4), however there is no way using an `OutputField` to access these decreased confidences. Should the results returned from a tree model probability always be normalized? If so is this feature of PMML unusable?

**Comment by vruusmann** [comment]
Probability and confidence estimates are two separate concepts. From the end user perspective, probabilities are required to sum to `1.0`, whereas confidences can sum to anything. It follows that missing value handlers can only affect confidence estimates.

You can access confidence estimates using `OutputField@feature="confidence"`.

I think that the JPMML-Evaluator library operates in agreement with the PMML specification. If you disagree, then please reopen this issue and be sure to provide a couple of data records that back your case.

**Comment by infiton** [comment]
apologies I didn't paste the correct PMML before (edited in the original comment).When I run the above PMML through jpmml evaluator `java -cp target/example-1.4-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample` with the above PMML and `temperature=40, outlook=NULL, humidity=70` I get:

```
Exception in thread "main" org.jpmml.evaluator.TypeCheckException: Expected org.jpmml.evaluator.HasRuleValues value, got org.jpmml.evaluator.tree.TreeModelEvaluator$3 value
	at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:502)
	at org.jpmml.evaluator.OutputUtil.getRuleValue(OutputUtil.java:544)
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:306)
	at org.jpmml.evaluator.tree.TreeModelEvaluator.evaluate(TreeModelEvaluator.java:133)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:431)
	at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:298)
	at org.jpmml.evaluator.Example.execute(Example.java:86)
	at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:180)
```

this error actually makes sense if you look at the allowed model/output combinations athttp://dmg.org/pmml/v4-3/Output.html where is says `OutputField@feature="confidence"` is only valid for `AssociationRules`

**Comment by vruusmann** [comment]
The value of the target field is probably a subclass of `org.jpmml.evaluator.tree.NodeScoreDistribution`, which implements `org.jpmml.evaluator.HasConfidence` marker interface.

So, if you really need to have those confidence estimates, then the following code should do the trick:
```Java
Object targetValue = result.get(FieldName.create("whatIdo"));
if(targetValue instanceof HasConfidence){
  HasConfidence hasConfidence = (HasConfidence)targetValue;
  System.out.println(hasConfidence.getConfidence("may play"));
}
```

It's probably an honest mistake by the DMG.org that `TreeModel` and `RuleSetModel` are not listed as "confidence"-enabled model types.

**Comment by infiton** [comment]
> It's probably an honest mistake by the DMG.org that TreeModel and RuleSetModel are not listed as "confidence"-enabled model types.

I agree

**Comment by infiton** [comment]
thank you for taking a look!

**Comment by vruusmann** [comment]
> It's probably an honest mistake by the DMG.org that TreeModel and RuleSetModel are not listed as "confidence"-enabled model types.

Then again, it doesn't mean that PMML vendors might not enable such "extensions" in their implementations.

I was expecting the JPMML-Evaluator library to permit the use of `OutputField@feature="confidence"` in this context. Will reopen this issue, implement this functionality, and also let the DMG.org know about the situation.
