### ISSUE TITLE
Text Mining Model conversion from python to java

### ISSUE THREAD

**Issue by ddeisadz** [jpmml/jpmml-evaluator#108]
Basically, we have exported our PMML model from python to Java and loaded it in already. However, we are having trouble evaluating user input strings based on the exported model to Java. The solution would be to preprocess/vectorize the same way we did it in python but we cannot figure that out. For our preprocessing, we use Text Vectorizer, and we are unable to use any vectorizers in the Java file. Do you have any suggestions?

**Comment by vruusmann** [comment]
Sample TF-IDF usage:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L355-L377

How does your Python code look like? This is most likely a conversion-side issue, so we should move over to the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) project.
