### ISSUE TITLE
Problems of using Guava Cache 

### ISSUE THREAD

**Issue by fightwin** [jpmml/jpmml-evaluator#109]
Hi, I have a problem about using Guava Cache. 
The following is my test code:
```
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.JAXBException;

import org.dmg.pmml.FieldName;
import org.dmg.pmml.PMML;
import org.jpmml.evaluator.CacheUtil;
import org.jpmml.evaluator.Evaluator;
import org.jpmml.evaluator.FieldValue;
import org.jpmml.evaluator.InputField;
import org.jpmml.evaluator.ModelEvaluatorFactory;
import org.jpmml.model.PMMLUtil;
import org.xml.sax.SAXException;

import com.google.common.cache.CacheBuilderSpec;

public class Test {
	public static void main(String[] args) throws FileNotFoundException, SAXException, JAXBException {
//		CacheUtil.setCacheBuilderSpec(CacheBuilderSpec.parse(""));
		PMML pmml = PMMLUtil.unmarshal(new FileInputStream("/Users/ben/Documents/2018020715.pmml"));
		ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
		final Evaluator evaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
		evaluator.verify();
		InputField tagInputField = evaluator.getInputFields().get(0);
		final Map<FieldName, FieldValue> args1 = new HashMap<FieldName, FieldValue>(1);
		args1.put(tagInputField.getName(), tagInputField.prepare("0qzr00,0w3woq"));
		for(int j = 0 ; j < 10 ; j++){
			new Thread(new Runnable() {
				
				@Override
				public void run() {
					for(int i = 0 ; i < 100000; i++){
						evaluator.evaluate(args1);
					}
				}
			}).start();
		}
	}
}

```
The [test.log](https://github.com/jpmml/jpmml-evaluator/files/1945386/test.log) is the runtime jstack file. In the case of multi thread running,  every thread will wait the lock of “com.google.common.cache.LocalCache$Segment.put() ”. The org.jpmml.evaluator.TextUtil.TermProcessor.process() is 
```
		@Override
		public List<String> process(){
			TextIndex textIndex = getTextIndex();
			FieldValue value = getValue();

			Cache<FieldValue, List<String>> termTokenCache = CacheUtil.getValue(textIndex, TextUtil.termTokenCaches, TextUtil.termTokenCacheLoader);

			List<String> tokens = termTokenCache.getIfPresent(value);
			if(tokens == null){	
				String string = value.asString();

				tokens = TextUtil.tokenize(textIndex, string);

				termTokenCache.put(value, tokens);
			}

			return tokens;
		}
```
Each execution of "termTokenCache.getIfPresent (value)" will not hit, because the CacheUtil use "private static CacheBuilderSpec cacheBuilderSpec = CacheBuilderSpec.parse("weakKeys");". . 

- Why does it use the policy of "weakKeys" instead of the Guava Cache's default policy?

**Comment by vruusmann** [comment]
What is your Google Guava version? According to `com.google.common.cache.Cache` Javadoc (eg. [here](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/cache/Cache.html)), all Cache implementation classes should be thread safe: "Implementations of this interface are expected to be thread-safe, and can be safely accessed by multiple concurrent threads".

So, the fact that `Cache#put` if blocking indicates a problem inside the Google Guava library(?).

> Why does it use the policy of "weakKeys" instead of the Guava Cache's default policy?

Fields `TextUtil#termTokenCaches` and `TextUtil#textTokenCaches` are caches-of-caches. The key type of the "parent" cache is `org.dmg.pmml.TextIndex`; the `weakKeys` cache management policy should ensure that whenever the a TextIndex element is no longer strongly referentiable (eg. the model has been undeployed), then the Google Guava library should purge all the related caches of related content.

Using `stringKeys`, or any other cache management ploicy, would cause these two caches-of-caches to consume all available memory in the application has been running for extended periods of time. There is currently no mechanism for manually cleaning caches.

**Comment by fightwin** [comment]
The Google Guava version is 14.0
if use the ```weakKeys ``` , the cache will use the ``` com.google.common.base.Equivalence.Identity ```
But if use the ``` strongKeys ``` , the cache will use the ``` com.google.common.base.Equivalence.Equals```
The following is their Implementations:
```
  static final class Equals extends Equivalence<Object>
      implements Serializable {
    
    static final Equals INSTANCE = new Equals();

    @Override protected boolean doEquivalent(Object a, Object b) {
      return a.equals(b);
    }
    @Override public int doHash(Object o) {
      return o.hashCode();
    }

    private Object readResolve() {
      return INSTANCE;
    } 
    private static final long serialVersionUID = 1;
  }
  
  static final class Identity extends Equivalence<Object>
      implements Serializable {
    
    static final Identity INSTANCE = new Identity();
    
    @Override protected boolean doEquivalent(Object a, Object b) {
      return false;
    }

    @Override protected int doHash(Object o) {
      return System.identityHashCode(o);
    }
 
    private Object readResolve() {
      return INSTANCE;
    }
    private static final long serialVersionUID = 1;
  }
```

Pay attention to the ```Identity.doHash() ``` , it uses  ``` System.identityHashCode() ```

That results in the failure to hit the cache every time the code （ ```evaluator.evaluate(args1)```） is executed. 

> Isn't it supposed to hit the cache when the the code （ ```evaluator.evaluate(args1)```） is executed for the second time?

**Comment by vruusmann** [comment]
> The Google Guava version is 14.0

If you upgrade to Google Guava 24.0-jre (at least temporarily for testing purposes), then does the problem persist?

**Comment by fightwin** [comment]
Both versions perform the same , the problem persists

The following is a part of `org.jpmml.evaluator.TextUtil.TermProcessor`:
```
@Override
public List<String> process(){
	TextIndex textIndex = getTextIndex();
	FieldValue value = getValue();

	Cache<FieldValue, List<String>> termTokenCache = CacheUtil.getValue(textIndex, TextUtil.termTokenCaches, TextUtil.termTokenCacheLoader);
	System.out.println(termTokenCache.size());
	List<String> tokens = termTokenCache.getIfPresent(value);
	if(tokens == null){
		String string = value.asString();

		tokens = TextUtil.tokenize(textIndex, string);

		termTokenCache.put(value, tokens);
	}

	return tokens;
}
```

I think that if the `pmml` file hasn't been changed , then it shound hit the `termTokenCache` , otherwise what is the use of the cache?
