### ISSUE TITLE
glm binomial predict  different results

### ISSUE THREAD

**Issue by vicenteAbad** [jpmml/jpmml-evaluator#110]
R code:
model.glm <- glm(formula= vs ~ wt + disp, data=mtcars, family=binomial(link = "probit"))
predict(model.glm, mtcars)

Mazda RX4
0.2698745

In jar aplication:
Mazda RX4
0.6063715859473016

Checking the results when the family is gaussian everything is ok, however when I choose binomial family I encounter the following problem

**Comment by vruusmann** [comment]
Check out the description of the `predict.glm` function:

> for a default binomial model the default predictions are of log-odds (probabilities on logit scale) and type = "response" gives the predicted probabilities.

Testing the predicted probabilities of binomial models:
```
model.glm <- glm(formula= vs ~ wt + disp, data=mtcars, family=binomial(link = "probit"))
predict(model.glm, mtcars, type = "response")
```

R prediction:
```
Mazda RX4
0.6063715859
```
