### ISSUE TITLE
Accessing the predictions of member models from the prediction of the top-level ensemble model

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-evaluator#118]
For example, it should be possible to access a collection of `org.jpmml.evaluator.tree.HasDecisionPath` objects when dealing with decision tree ensemble models (Random Forest, GBT).

See jpmml/jpmml-xgboost#25

Possibly, the prediction of a `MiningModel` element should implement some marker interface to indicate the availability of elementary predictions.

**Comment by USCYuandaDu** [comment]
Hi @vruusmann!
I'm really impressed your fast reply and wonderful idea. I read your code carefully, you really do a lot to the open source community.
Recently I have an idea, take xgboost as an example, as an user like me. Here is I how to use jpmml,  
First prepare the train the xgboost model with data and spark, then get a pipeline model, then feed to jpmml to parse the pipeline. But you know xgboost was hard to analyze the model. What if we do not write the pmml generated into the disk, but use the pmml-evaluator to train the data again, at this time, we could get the record count number and other useful message. 
I've tried your method mentioned above, but it seems like if we used a Classification MiningModel which was a Chain method, it's hard to reach each trees' evaluator.
But It seems more easy and nature to add the node record count when evaluate the Tree within the method handleTree(trail, root, context). We can also an option parameter which default value is false.
I could give it a shot if you are too busy.
What do you think about it?
Bests,
Yuanda
