### ISSUE TITLE
Boolean input variables not recognised by evaluator function.

### ISSUE THREAD

**Issue by warner121** [jpmml/jpmml-evaluator#12]
I have the following R code for generating 2 csv and 2 pmml files based on the iris dataset:

    data(iris)
    library(pmml)
    
    # build a model for Sepal.Length based on remaining variables
    model.glm <- glm(Sepal.Length ~ ., data=iris)
    saveXML(pmml(model.glm), "iris.glm.pmml")
    
    # write csv file for testing
    write.csv(iris, 'iris.csv', quote=FALSE, row.names=FALSE)
    
    # set remaining variables to booleans
    iris$Sepal.Width <- as.logical(iris$Sepal.Width > 3)
    iris$Petal.Length <- as.logical(iris$Petal.Length > 4)
    iris$Petal.Width <- as.logical(iris$Petal.Width > 1)
    iris$Species   <- as.logical(iris$Species=='setosa')
    
    # rebuild model for Sepal.Length
    model.glm <- glm(Sepal.Length ~ ., data=iris)
    saveXML(pmml(model.glm), "iris.glm.bool.pmml")
    
    # write csv file for testing
    write.csv(iris, 'iris.bool.csv', quote=FALSE, row.names=FALSE)

The problem becomes apparent when doing predictions. The files `iris.csv` and `iris.glm.pmml` produce the desired output. The files `iris.bool.csv` and `iris.glm.bool.pmml` produce the same value 
for every record, regardless of the input data.

**Comment by warner121** [comment]
I can work-around the issue by converting the booleans to 0/1 integers as below:

    # set booleans to integers
    iris$Sepal.Width <- as.integer(iris$Sepal.Width)
    iris$Petal.Length <- as.integer(iris$Petal.Length)
    iris$Petal.Width <- as.integer(iris$Petal.Width)
    iris$Species   <- as.integer(iris$Species)
    
    # rebuild model for Sepal.Length
    model.glm <- glm(Sepal.Length ~ ., data=iris)
    saveXML(pmml(model.glm), "iris.glm.int.pmml")
    
    # write csv file for testing
    write.csv(iris, 'iris.int.csv', quote=FALSE, row.names=FALSE)

**Comment by vruusmann** [comment]
The standard R "pmml" package has produced an invalid `iris.glm.bool.pmml` file:
* The `GeneralRegressionModel/FactorList` element is not populated
* The `GeneralRegressionModel/PPMatrix` element is not populated.

A similar issue was discussed in the JPMML mailing list last week:
https://groups.google.com/d/msg/jpmml/paKwqk9Sm-g/odnLm9mPAQAJ

As a rule of thumb, if you ever encounter a situation where the JPMML-Evaluator library behaves differently from other PMML producer or consumer software, then you can safely assume 99+% of time that the JPMML-Evaluator library is correct and the other software is wrong.

If you want to test classification-type logistic regression models then you may want to take a look at the JPMML-SkLearn project. It supports the `sklearn.linear_model.LogisticRegression` model type now.
