### ISSUE TITLE
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$evaluationFunction$1$1: (struct<Sepal_Length:double,Sepal_Width:double,Petal_Length:double,Petal_Width:double>) => struct<Species:string,Probability_setosa:double,Probability_versicolor:double,Probability_virginica:double,Node_Id:string>)

### ISSUE THREAD

**Issue by BinbinSongg** [jpmml/jpmml-evaluator#120]
hello, vruusmann
thanks for your contributions to this project. 
i simply download DecisionTreeIris.pmml and PMMLTransformerTest.scala from https://github.com/jpmml/jpmml-evaluator-spark/blob/master/src/test 

and, want to run it on local, but when i set the all the dependencies (graph2) and import all needed files (graph 2)
graph1:
<img width="692" alt="screen shot 2018-07-08 at 6 08 30 pm" src="https://user-images.githubusercontent.com/20677262/42418668-969068d6-82d7-11e8-8c2f-806c006600d4.png">

graph2: 
<img width="415" alt="screen shot 2018-07-08 at 6 08 07 pm" src="https://user-images.githubusercontent.com/20677262/42418671-a5d99e70-82d7-11e8-9c24-1ce4dec4a2ea.png">

error message 

`Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$evaluationFunction$1$1: (struct<Sepal_Length:double,Sepal_Width:double,Petal_Length:double,Petal_Width:double>) => struct<Species:string,Probability_setosa:double,Probability_versicolor:double,Probability_virginica:double,Node_Id:string>)`

i get the errors, and i has no idea how to solve the problem, can you give me some advices, thanks

**Comment by vruusmann** [comment]
Your application classpath is a complete mess - it is mixing JPMML-Model and JPMML-Evaluator library versions 1.3.X and 1.4.X. In addition to that, I believe that you haven't paid any attention to shading your Apache Spark application properly, which means that there are Apache Spark built-in JPMML-Model 1.2.X creeping in as well.

To solve this issue, please see JPMML-Evaluator-Spark documentation about setting up the application classpath.
