### ISSUE TITLE
visitorBattery in scala. LocatorNullifier.class

### ISSUE THREAD

**Issue by LittileFatNoRun** [jpmml/jpmml-evaluator#121]
When i try to use visitorBattery in scala, there is no LocatorNullifier.class method. So i can't add it.Is there any solution on this problem.

**Comment by vruusmann** [comment]
Class `org.jpmml.model.visitors.LocatorNullifier` comes from the JPMML-Model library.

The code snippet `LocatorNullifier.class` means Java class literal, not a field or method invocation. In other words, there is no `LocatorNullifier#class` field, or `LocatorNullifier#class()` method.

There's probably some special Scala syntax for "accessing" Java class literals.
