### ISSUE TITLE
FieldValue prepare(InputField inputField, Object value) no more available

### ISSUE THREAD

**Issue by anwarchk** [jpmml/jpmml-evaluator#123]
I upgraded my code from 1.3.8 to 1.4.3, but now stuck with a compilation error at this point:

`FieldValue value = EvaluatorUtil.prepare(modelInputField, realValue);`  //prepare is no more available on the class EvaluatorUtil

Are there any replacement or how do I upgrade keeping the functionality same ?

thanks
Anwar

**Comment by vruusmann** [comment]
It's all in the README file. You might want to diff README between versions to see what else has changed.

JPMML-Evaluator 1.3.X:
```Java
FieldValue value = EvaluatorUtil.prepare(modelInputField, realValue);
```

JPMML-Evaluator 1.4.X:
```Java
FieldValue value = modelInputField.prepare(realValue);
```

**Comment by anwarchk** [comment]
Thank you !
