### ISSUE TITLE
Error while evaluating pmml.

### ISSUE THREAD

**Issue by gauravbansal2000** [jpmml/jpmml-evaluator#125]
We were training a lightGBM(python)  model with only continuous features. While evaluating the pmml 
we got error like _.InvalidResultException: Field "f1" cannot accept user input value 0.835_. After a bit of investigation we found that it was because the leftMargin and rightMargin of that feature were 0.003044448954739192 and 0.8295821274646568 respectively as read from the pmml file itself. And those margins were calculated by seeing the historical min and max in the training data. So are there any edge cases (apart from very high or low values ) you wanted to handle by introducing those checks?

**Comment by vruusmann** [comment]
This behaviour is a feature, not a bug - a model should not be used to make predictions outside of its applicability domain (as defined by training data).

> We were training a lightGBM(python) model with only continuous features.

If you're using SkLearn2PMML package, then it's possible to disable the generation/storage of applicability domain information. Simply set `ContinuousDomain(with_data = False)` for "problematic" columns:

```Python
pipeline = PMMLPipeline([
  ("mapper", DataFrameMapper([
    (["f1"], [ContinuousDomain(with_data = False)]) # THIS!
  ])),
  ("regressor", LGBMRegressor())
])
```

**Comment by puqugithub** [comment]
I encounted the same problem. Any way to turn off the left/right margin in evaluation? :)

**Comment by yeikel** [comment]
I am also interested on this if applicable.
