### ISSUE TITLE
javax.xml.bind.UnmarshalException: unexpected element

### ISSUE THREAD

**Issue by BinbinSongg** [jpmml/jpmml-evaluator#131]
when i tried the test  sample (under path jpmml-evaluator-spark/src/test/scala/org/jpmml/evaluator/spark/PMMLTransformerTest.scala) in local mode in my computer, everything is okay! and i can get the prediction result. 

But when i upload jar file and model to our company's cluster, i get the error below

`Exception in thread "main" javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.dmg.org/PMML-4_3", local:"PMML"). Expected elements are <{http://www.dmg.org/PMML-4_2}ARIMA>,<{http://www.dmg.org/PMML-4_2}Aggregate>,<{http://www.dmg.org/PMML-4_2}Alternate>,<{http://www.dmg.org/PMML-4_2}Annotation>,<{http://www.dmg.org/PMML-4_2}Anova>,<{http://www.dmg.org/PMML-4_2}AnovaRow>,<{http://www.dmg.org/PMML-4_2}AntecedentSequence>,<{http://www.dmg.org/PMML-4_2}AnyDistribution>,<{http://www.dmg.org/PMML-4_2}Application>........................................`

And, my local environment is same with cluster environment, the version infomation is below
spark 2.1.1 
scala 2.11.8

the only difference, i  think is my local system is unix and cluster system is linux

look forwarding to your reply
 i have got stuck for two days and have no idea about what's going wrong..

**Comment by vruusmann** [comment]
> the version infomation is below:
> spark 2.1.1

Apache Spark 2.0, 2.1 and 2.2 distributions contain an outdated JPMML-Model library (version 1.2.15). It's a "built-in" library, which is added to the first position on Apache Spark application classpath, and which then shadows all newer JPMML-Model library versions (should be at least 1.3.X if PMML 4.3 support is required).

To solve this problem, you need to package your Apache Spark application properly. It has been extensively documented elsewhere, and I'm not going to repeat it here.

Also, see https://issues.apache.org/jira/browse/SPARK-15526
