### ISSUE TITLE
org.jpmml.evaluator.TypeCheckException: Expected STRING, but got null at lineMap<FieldName, ?> results = modelEvaluator.evaluate(arguments);

### ISSUE THREAD

**Issue by hydraluicdata** [jpmml/jpmml-evaluator#132]
private void printArgumentsOfModel(ModelEvaluator<?> modelEvaluator, PMML pmml) throws  FileNotFoundException {
		String csvFileToRead = "E:/hyd_dataset_test1.csv";
		String dataLine;
		BufferedReader dataLines = new BufferedReader(new FileReader(csvFileToRead));
		try {
			while (!dataLines.readLine().isEmpty()) {
				dataLine=dataLines.readLine();
				  Map<FieldName, FieldValue> arguments = readArgumentsFromLine(dataLine, modelEvaluator); 
			  modelEvaluator.verify();
			
				  // evaluate the model with the given fields
				  Map<FieldName, ?> results = modelEvaluator.evaluate(arguments);
				  // read result fields
				  FieldName targetName =  modelEvaluator.getTargetField();
				  Object targetValue = results.get(targetName);
				  //ProbabilityClassificationMap nodeMap = (ProbabilityClassificationMap) targetValue;
				  ProbabilityDistribution nodeMap=(ProbabilityDistribution)targetValue;
				  System.out.println("Prediction': " + nodeMap.getProbability("CE_median"));
				
				}
		} catch (IOException e) {
			e.printStackTrace();
		}

		
	}

values in arguments is {CE_median=ContinuousDouble{opType=CONTINUOUS, dataType=DOUBLE, value=46.93}}

**Comment by vruusmann** [comment]
This report does not contain any actionable information.

Most likely, the input data record (`arguments`) does not contain a value for some required field.
