### ISSUE TITLE
MiningModelEvaluator multipleModelMethod with weightedAverage not support probability OutputField feature 

### ISSUE THREAD

**Issue by xbkaishui** [jpmml/jpmml-evaluator#14]
my scenario is this , I train an random forest pmml file 
I use multipleModelMethod=weightedAverage , and want to output  label's multi class probability 
the pmml file like this 
 
![2015-10-17 7 54 13](https://cloud.githubusercontent.com/assets/1477791/10558608/e4959c48-7508-11e5-852f-28719f74e01b.png)
￼

then it throws an Exception   

org.jpmml.evaluator.TypeCheckException: Expected org.jpmml.evaluator.HasProbability, but got org.jpmml.evaluator.ClassificationMap ({0=0.6526508348685987, 1=0.3473491651314011})
	at org.jpmml.evaluator.OutputUtil.asResultFeature(OutputUtil.java:848)
	at org.jpmml.evaluator.OutputUtil.getProbability(OutputUtil.java:478)
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:182)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:117)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:85)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:79)
	at com.alipay.mymdp.model.component.impl.pmml.engine.PmmlComponentEngine.execute(PmmlComponentEngine.java:49)
	at com.alipay.mymdp.model.component.impl.pmml.engine.PmmlComponentEngine.executePmmlComponentEngine(PmmlComponentEngine.java:35)
	at com.alipay.mymdp.model.component.impl.pmml.engine.TestPmmlComponentEngine.testRF2PmmlCom

**Comment by vruusmann** [comment]
Please upgrade to the latest version. The support for the `MiningModel` element was heavily refactored between versions 1.1.18 and 1.2.0.

I can see from your stack trace that you are using some 1.1.X version, because the class `org.jpmml.evaluator.ClassificationMap` does not exist in 1.2.X versions (it was renamed to class `org.jpmml.evaluator.Classification` in commit 3f00adba43).

**Comment by xbkaishui** [comment]
HI vruusmann ,  I test Evaluator with version 1.2.5 , the issue is fixed . I have one question the requirement of JDK is 1.7 , is it possible that JDK 1.6 can support this version ?

**Comment by vruusmann** [comment]
Indeed, JPMML-Evaluator version 1.1.X supports JDK 1.6 and newer, whereas JPMML-Evaluator version 1.2.X supports JDK 1.7 and newer.

Technically, it shouldn't be too difficult to back-port current codebase to JDK 1.6. It will require undoing some syntax changes (eg. replacing the diamond operator) and restoring JAXB dependencies.

However, we have no intention of doing such thing ourselves. According to [Oracle's Java SE Support Roadmap] (http://www.oracle.com/technetwork/java/javase/eol-135779.html), the end of life for JDK 1.6 was in February 2013 (and for JDK 1.7 it was in April 2015). The majority of our customers are running JDK 1.8 anyway, so it is likely that the upcoming JPMML-Evaluator version 1.3 will support JDK 1.8 and newer.

**Comment by xbkaishui** [comment]
great  got it. thx
