### ISSUE TITLE
Support for IForest

### ISSUE THREAD

**Issue by cossy** [jpmml/jpmml-evaluator#144]
To my knowledge, jpmml-evaluator doesn't support Isolation Forest.
I wanted to make anomaly identification using IForest model in Java.
I had pmml file generated by sklearn in python.
There is no function to load new training datas and update model in EvaluatorBuilder or Evaluator.
Would be of great help, if someone could suggest alternate solutions as well.

**Comment by vruusmann** [comment]
> To my knowledge, jpmml-evaluator doesn't support Isolation Forest.

The JPMML ecosystem has been supporting decision tree-based anomaly detection models for **years** now.

> There is no function to load new training datas and update model in EvaluatorBuilder or Evaluator.

See my earlier comment here:
https://github.com/jpmml/jpmml-lightgbm/issues/18#issuecomment-462645925
