### ISSUE TITLE
ResultsField, ModelField, OutField parsing and extraction 

### ISSUE THREAD

**Issue by ravikkaushik** [jpmml/jpmml-evaluator#147]
@vruusmann, based on a number of OutputField names in binomial and multinomial classification, probabilities can range from as little as one to many. We want to specifically pick up the PMML outputField based on a selection

For example, lets say I want to pick up the probability of Iris-setosa among the 9 outputs in the XML below, does the current API provide a way to search through the PMML and pick up by "feature" and "value"

1. I am looking for specifically, outputField.getFeature() and outputField.getValue() similar to outputField.getDisplayName() and outputField.getName()

2. Can we extract PMML Application Name and Version from the PMML Parser.
thanks! 

```
<Output>
<OutputField name="I_species" displayName="Into: species" optype="categorical" dataType="string" targetField="species" feature="predictedValue"/>
<OutputField name="U_species" displayName="Unnormalized Into: species" optype="categorical" dataType="string" targetField="species" feature="predictedDisplayValue"/>
<OutputField name="E_species" displayName="Error Function: species" optype="continuous" dataType="double" targetField="species" feature="standardError"/>
<OutputField name="R_speciesIris_setosa " displayName="Residual: species=Iris-setosa" optype="continuous" dataType="double" targetField="species" feature="residual" value="IRIS-SETOSA"/>
<OutputField name="R_speciesIris_versicolor" displayName="Residual: species=Iris-versicolor" optype="continuous" dataType="double" targetField="species" feature="residual" value="IRIS-VERSICOLOR"/>
<OutputField name="R_speciesIris_virginica " displayName="Residual: species=Iris-virginica" optype="continuous" dataType="double" targetField="species" feature="residual" value="IRIS-VIRGINICA"/>
<OutputField name="P_speciesIris_setosa " displayName="Predicted: species=Iris-setosa" optype="continuous" dataType="double" targetField="species" feature="probability" value="IRIS-SETOSA"/>
<OutputField name="P_speciesIris_versicolor" displayName="Predicted: species=Iris-versicolor" optype="continuous" dataType="double" targetField="species" feature="probability" value="IRIS-VERSICOLOR"/>
<OutputField name="P_speciesIris_virginica " displayName="Predicted: species=Iris-virginica" optype="continuous" dataType="double" targetField="species" feature="probability" value="IRIS-VIRGINICA"/>
</Output>
```

**Comment by vruusmann** [comment]
This question is about API usage, and should be asked in the JPMML mailing list instead: https://groups.google.com/forum/#!forum/jpmml

> We want to specifically pick up the PMML outputField based on a selection.

Recommended approach - standardize your output field names by performing a "soft rename" (see https://github.com/jpmml/jpmml-evaluator/issues/127), and then look up the right output field the standardized name. For example, all probability-type output fields could be "soft-renamed" to `probability(<target category>)`.

It seems that your PMML producer application uses `P_<target name>_<target category>` pattern for renaming output fields. You could standardize them like this:

```java
ModelEvaluatorBuilder builder = new ModelEvaluatorBuilder(...)
  .setResultMapper(new ResultMapper(){
    @Override
    public FieldName apply(FieldName name){
      String value = name.getValue();
      if(value.startsWith("P_")){
        value = "probability(" + value.substring(value.lastIndexOf('_') + 1) + ")";
        return FieldName.create(value);
      }
      return name;
    }
  });
```

Additionally, if you'd like to suppress some output field(s), then it's possible to specify an appropriate `OutputFilter` implementation class via `ModelEvaluatorBuilder#setOutputFilter(OutputFilter)`.

> Does the current API provide a way to search through the PMML and pick up by "feature" and "value"

All `org.jpmml.evaluator.ModelField` subclasses expose the underlying Field element via `ModelField#getField()`.
```java
List<org.jpmml.evaluator.OutputField> outputFields = evaluator.getOutputFields();
for(OutputField outputField : outputFields){
  org.dmg.pmml.OutputField pmmlOutputField = outputField.getField(); // THIS!
}
```

It's all covered in the README.md file, in section "Advanced usage": https://github.com/jpmml/jpmml-evaluator#querying-the-data-schema-of-models

**Comment by ravikkaushik** [comment]
thanks! Will use the groups forum for additional Qs
