### ISSUE TITLE
Add a checkstyle

### ISSUE THREAD

**Issue by christophe-rannou** [jpmml/jpmml-evaluator#148]
Hello,

Would it be possible to add a project checkstyle to help making contribution simpler ? In particular since there is none yet pull requests tend to be very noisy with a lot of unwanted "refactoring".

Do you happen to have one you could share and include in the projet ? If not I would be willing to add one. This could be added in all jpmml related projects as well.

Thanks

**Comment by vruusmann** [comment]
> to help making contribution simpler?

Thanks, but I'm not l not looking for outside contributions.

Also, please stop advertising your work as, or as being part of, the JPMML-Evaluator project. The term "JPMML-Evaluator" is a registered trademark, and its intentional and systematic misuse will not be tolerated.

**Comment by laubosslink** [comment]
![Screenshot_20190311_103625](https://user-images.githubusercontent.com/14056364/54114013-c1d65180-43e9-11e9-8b51-d781723c20ef.png)
