### ISSUE TITLE
PMML generator does not support linear_model.LinearRegression

### ISSUE THREAD

**Issue by agrimabahl** [jpmml/jpmml-evaluator#154]
My pmml generator is failing while trying to evaluate a linear regression model, but works for the Logistic Regression model, with everything else remaining the same. Is linear regression pmml generation supported in sklearn2pmml? If so, how is it achieved?

**Comment by vruusmann** [comment]
This issue (PMML generation) belongs to some other project, not here.

> Is linear regression pmml generation supported in sklearn2pmml?

Yes it is.

> If so, how is it achieved?

Search for "LinearRegression" here:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py
