### ISSUE TITLE
Problem when evaluating xgboost

### ISSUE THREAD

**Issue by masosky** [jpmml/jpmml-evaluator#156]
Hi VIlu,

We have upgrade our jpmml-evaluator library to 1.4.9 and now the model is not working.
We are using PMML 4.3 -> xgboost
We are receiving an error like this:
```
org.jpmml.evaluator.TypeCheckException: Expected org.jpmml.evaluator.HasProbability value, got org.jpmml.evaluator.Classification value
	at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:538)
	at org.jpmml.evaluator.OutputUtil.getProbability(OutputUtil.java:480)
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:209)
	at org.jpmml.evaluator.ModelEvaluator.evaluateInternal(ModelEvaluator.java:660)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateInternal(MiningModelEvaluator.java:207)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:548)
	at Main.main(Main.java:59)
```

Can you help us?

Thank you

**Comment by vruusmann** [comment]
> We are using PMML 4.3 -> xgboost

Show me your model.

All JPMML-XGBoost, JPMML-R, JPMML-H2O and JPMML-SkLearn projects include XGBoost integration tests, and they work perfectly fine with JPMML-Evaluator version 1.4.9.

**Comment by masosky** [comment]
Thanks for your answer.
I attach the pmml file.
The evaluation class is the following:
`import org.dmg.pmml.DataType;
import org.dmg.pmml.FieldName;
import org.dmg.pmml.OpType;
import org.dmg.pmml.PMML;
import org.jpmml.evaluator.CategoricalValue;
import org.jpmml.evaluator.ContinuousValue;
import org.jpmml.evaluator.ModelEvaluator;
import org.jpmml.evaluator.ModelEvaluatorFactory;
import org.jpmml.evaluator.visitors.ElementInternerBattery;
import org.jpmml.evaluator.visitors.ElementOptimizerBattery;
import org.jpmml.model.JAXBUtil;
import org.jpmml.model.PMMLUtil;
import org.jpmml.model.VisitorBattery;
import org.jpmml.model.filters.ImportFilter;
import org.jpmml.model.visitors.AttributeInternerBattery;
import org.jpmml.model.visitors.AttributeOptimizerBattery;
import org.jpmml.model.visitors.ListFinalizerBattery;
import org.jpmml.model.visitors.LocatorNullifier;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.util.ValidationEventCollector;
import javax.xml.transform.Source;
import javax.xml.transform.sax.SAXSource;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

public class Main2 {

    public static void main(String[] args) {
        try {
            PMML pmml = readPMML(new File("/home/xavier.mas/Desktop/dummy.pmml"));
            VisitorBattery visitorBattery = new VisitorBattery();
            visitorBattery.add(LocatorNullifier.class);
            visitorBattery.addAll(new AttributeOptimizerBattery());
            visitorBattery.addAll(new ElementOptimizerBattery());
            visitorBattery.addAll(new AttributeInternerBattery());
            visitorBattery.addAll(new ElementInternerBattery());
            visitorBattery.addAll(new ListFinalizerBattery());
            visitorBattery.applyTo(pmml);

            final ModelEvaluator<?> modelEvaluator = ModelEvaluatorFactory.newInstance().newModelEvaluator(pmml);
            final Map<FieldName, ?> evaluate = modelEvaluator.evaluate(getFeatures());
            System.out.println(evaluate);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public static PMML readPMML(File file) throws Exception {
        try (InputStream is = new FileInputStream(file)) {
            return PMMLUtil.unmarshal(is);
        }
    }

    private static Map<FieldName, Object> getFeatures() {
        final HashMap<FieldName, Object> map = new HashMap<>();

        map.put(FieldName.create("Petal.Length"), ContinuousValue.create(DataType.DOUBLE, OpType.CONTINUOUS, -0.183333d));
        map.put(FieldName.create("Petal.Width"), ContinuousValue.create(DataType.DOUBLE, OpType.CONTINUOUS, 135.0d));
        //map.put(FieldName.create("Species"), CategoricalValue.create(DataType.STRING, OpType.CATEGORICAL, "1"));

        return map;
    }

}

[model.zip](https://github.com/jpmml/jpmml-evaluator/files/3232173/model.zip)
`

**Comment by vruusmann** [comment]
> And the model:
> model.zip

Got it - looks like you're trying to evaluate models that have been generated by the [legacy R/Rattle `pmml` package](https://cran.r-project.org/package=pmml).

I would argue that it's generating invalid markup. Specifically, it does field scoping wrong, so that member model predictions are not visible at the top level. An invisible prediction becomes a `null` value, which cannot be legally cast to `org.jpmml.evaluator.HasProbability` (and raises the above `o.j.e.TypeCastException`).

IIRC, the JPMML-Evaluator library has never been able to deal with those R/Rattle generated XGBoost file - it's not related to the 1.4.9 version in any way.

Why don't you switch to the [new `r2pmml` package](https://github.com/jpmml/r2pmml) like normal people?

**Comment by masosky** [comment]
Thanks for the answer. 
Well, actually I just generated a dummy model in order to test it. 
It is a problem about how our DS department works but probably we will use the library that you have said.

Thanks a lot!
