### ISSUE TITLE
Exception while evaluating GBDTLR pmml

### ISSUE THREAD

**Issue by shanyuqiang** [jpmml/jpmml-evaluator#158]
```
{position=0, userc_id=39285472, job_base_job_id=18579079, job_base_job_kind=2, sim_score=0.0, job_base_dqfirst=50020, job_base_jobtitle=220240.0, job_base_edu=401, job_base_agelow=1.0, job_base_agehigh=1.0, job_base_workyears=2.0, job_base_industryfirst=50, job_base_pubtime=5, job_base_refreshtime=0, job_base_salaryhigh=5.0, job_base_salarylow=3.0, job_base_compscale=30, job_base_compkind=10, job_base_feedbackperiod=7, job_act_collect_cnt=4.0, job_act_app_show_cnt_3=242.0, job_act_app_search_view_cnt_3=14.0, job_act_app_search_apply_cnt_3=1.0, job_act_app_show_cnt_7=256.0, job_act_app_search_view_cnt_7=15.0, job_act_app_search_apply_cnt_7=1.0, job_act_app_show_cnt_15=334.0, job_act_app_search_view_cnt_15=22.0, job_act_app_search_apply_cnt_15=1.0, job_act_app_view_res_level_avg=3.0, job_act_app_apply_res_level_avg=2.0, userc_base_workyears=2, userc_base_age=3, userc_base_dq=50020, userc_base_wantdq=50020, userc_base_yearsal=2, userc_base_salaryhighavg=0.0, userc_base_salarylowavg=0.0, userc_base_logindays=2, userc_base_jobtitle=240030, userc_base_wantjobtitle=240030.0, userc_base_industry=220, userc_base_wantindustry=210, userc_base_resrefreshtime=18, userc_base_subordinates=5.0, userc_base_reslevel=1, userc_base_edu=400, userc_base_sex=0, userc_base_ecompscale=998, userc_base_ecompkind=998, userc_act_job_app_cv_dq_fav=0.0, userc_act_job_app_cv_jobtitle_fav=0.0, userc_act_job_app_cv_edu_fav=0.0, userc_act_job_app_cv_workyears_fav=0.0, userc_act_job_app_cv_salaryhigh_fav=0.0, userc_act_job_app_cv_salarylow_fav=0.0, userc_act_job_app_cv_industry_fav=0.0, userc_act_job_app_ct_dq_fav=0.93, userc_act_job_app_ct_edu_fav=0.13, userc_act_job_app_ct_workyears_fav=0.6, userc_act_job_app_ct_salaryhigh_fav=0.13, userc_act_job_app_ct_salarylow_fav=0.33, userc_act_job_app_ct_industry_fav=0.27, userc_act_job_app_filter_dq_fav=0.86, userc_act_job_app_filter_salaryhigh_fav=0.0, userc_act_job_app_filter_salarylow_fav=0.0, userc_act_job_app_filter_industry_fav=0.0, userc_act_job_app_filter_compkind_fav=0.0, userc_act_job_app_filter_compscale_fav=0.0, query_act_job_ct_workyears_fav=0.49, query_act_job_ct_jobtitle_fav=0.33, query_act_job_ct_industryfirst_fav=0.21, query_act_job_ct_dqfirst_fav=0.06, query_act_job_ct_edu_fav=0.29, query_act_job_cv_workyears_fav=0.51, query_act_job_cv_jobtitle_fav=0.36, query_act_job_cv_industryfirst_fav=0.20, query_act_job_cv_dqfirst_fav=0.06, query_act_job_cv_edu_fav=0.31, query_act_show_cnt_7=178593.0, query_act_view_cnt_7=4113.0, query_act_apply_cnt_7=1139.0, query_act_show_cnt_30=720380.0, query_act_view_cnt_30=16816.0, query_act_apply_cnt_30=4931.0, dq_transfer=0.744, industry_transfer=0.063, jobtitle_transfer=0.032, apv3=0.071, apv7=0.067, apv15=0.045, vps3=0.058, vps7=0.059, vps15=0.066}
```

```
Exception in thread "main" org.jpmml.evaluator.TypeCheckException: Expected double value, got missing value (null)
	at org.jpmml.evaluator.TypeUtil.toDouble(TypeUtil.java:660)
	at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:439)
	at org.jpmml.evaluator.mining.MiningModelUtil.aggregateValues(MiningModelUtil.java:75)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateRegression(MiningModelEvaluator.java:274)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:236)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:213)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:489)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:293)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:239)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:208)
```

**Comment by vruusmann** [comment]
> Exception in thread "main" org.jpmml.evaluator.TypeCheckException: Expected double value, got missing value (null)

One of the member decision tree models has produced a missing prediction, because one of its required inputs was missing.

Your input data record is incomplete. There's not enough information in it to make a prediction.

Besides, you should consider upgrading your JPMML-Evaluator version, as newer versions implement proper missing prediction handling (per http://mantis.dmg.org/view.php?id=178), and will throw a more informative exception.

**Comment by shanyuqiang** [comment]
> > Exception in thread "main" org.jpmml.evaluator.TypeCheckException: Expected double value, got missing value (null)
> 
> One of the member decision tree models has produced a missing prediction, because one of its required inputs was missing.
> 
> Your input data record is incomplete. There's not enough information in it to make a prediction.
> 
> Besides, you should consider upgrading your JPMML-Evaluator version, as newer versions implement proper missing prediction handling (per http://mantis.dmg.org/view.php?id=178), and will throw a more informative exception.

Thank you for your reply

This is my python code 

```
 gbdt = GradientBoostingClassifier(n_estimators=50, random_state=10, subsample=0.7, max_depth=7, min_samples_split=900)
lr= LogisticRegression()
pipeline = PMMLPipeline([
    ("classifier", GBDTLR(gbdt,lr))
])
pipeline.fit(X_train, y_train)
sklearn2pmml(pipeline, "GBDT_LR.pmml", with_repr = True)
```

I have upgraded my JPMML-Evaluator version from 1.3.11 to 1.4.11
When I copy  a input line training sample in Python(So there is no missing features) and execute Evaluator in Java, the exception like this

```
 Exception in thread "main" org.jpmml.evaluator.MissingValueException: The value for field "decisionFunction" is not defined
	at org.jpmml.evaluator.EvaluationContext.lookup(EvaluationContext.java:97)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:550)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:274)
	at org.jpmml.evaluator.ModelEvaluator.evaluateInternal(ModelEvaluator.java:681)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateInternal(MiningModelEvaluator.java:207)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:580)
```

But I find the pmml file already contains  decisionFunction

```
<Output>
                                          <OutputField name="decisionFunction" optype="continuous" dataType="double" feature="predictedValue" isFinalResult="false"/>
                                   </Output>
```

**Comment by vruusmann** [comment]
> I have upgraded my JPMML-Evaluator version from 1.3.11 to 1.4.11
> Exception in thread "main" org.jpmml.evaluator.MissingValueException: The value for field "decisionFunction" is not defined

As you can see, the new exception is much more informative, telling you that the first segment did not provide the value of `decisionFunction` field.

> But I find the pmml file already contains decisionFunction

The PMML document contains a *field declaration*.

When you execute this PMML document with a data record, then this field declaration gets evaluated, producing a *field value*.

In your case, this field declaration evaluates to a missing value, which is then rejected by the second segment (by throwing a `MissingValueException`).

The most common cause for a missing prediction is missing input. Don't waste your time looking for a bug in the JPMML software stack (SkLearn2PMML/JPMML-SkLearn/JPMML-Evaluator); the problem is in your testing data.

**Comment by vruusmann** [comment]
The PMML representation of `GBDT+LR` contains a top-level `MiningModel/Segmentation@x-missingPredictionTreatment="returnMissing"` attribute.

Therefore, it should silently return a missing prediction after the first segment, and not proceed to evaluating the segment at all (and throwing a `MissingValueException` in there).

This needs investigating. Most likely, if the missing prediction check (`"return missing"`) fires, then the Output element shouldn't be evaluated at all.

**Comment by shanyuqiang** [comment]
Thanks for your help and I will check again, Thanks a lot!
