### ISSUE TITLE
Collection value cannot be used in comparison operations-PMML document

### ISSUE THREAD

**Issue by josaomar2** [jpmml/jpmml-evaluator#160]
I am sorry for the previous issue, I am new here on Github and I didn't know that.

The exception message I got is "Collection value cannot be used in comparison operations".

I have created an Array List of Floats `[1.0, 1.0, 0.0023, 0.003, 100.0, 518.67, 643.02, 1585.29, 1398.21, 14.62, 21.61, 553.9, 2388.04, 9050.17, 1.3, 47.2, 521.72, 2388.03, 8125.55, 8.4052, 0.03, 392.0, 2388.0, 100.0, 38.86, 23.3735]` and I want to predict this line.

My code is:
```java
for(InputField inputfield: inputfields){
	FieldName inputfieldName=inputfield.getName();
	Object rawValue=analogs;
	FieldValue inputfieldValue=inputfield.prepare(rawValue);
	arguments.put(inputfieldName, inputfieldValue);
}
```
where analog is the list I created. When I try to prepare I get the exception message presented above. The exception also shows where is the error in the PMML document:
```xml
<SimplePredicate field="double(unit number)" operator="lessOrEqual" value="14.5"/>
```

but I still don't get it.
Can you please tell me how to resolve so?

Sorry again for the previous issue

**Comment by vruusmann** [comment]
> The exception message I got is "Collection value cannot be used in comparison operations".

If the exception says that you cannot use a collection-type field value with this operation, then why are you still generating and passing a collection value?

The computer won't change its mind about it ever, guaranteed.

> &lt;SimplePredicate field="double(unit number)" operator="lessOrEqual" value="14.5"/&gt;

The value of the "unit number" field must be a **scalar** value for the comparison to succeed.

If you have a collection of data rows to evaluate, then you need to iterate over the rows of this collection one-by-one, and prepare each row as a `java.util.Map` of scalar values.

You're probably trying to pass many rows at once (like one typically does in eg. Scikit-Learn's `predict(X)` and `predict_proba(X)` methods). The JPMML-Evaluator library uses a different API/abstraction.
