### ISSUE TITLE
error ReportingFloatValue

### ISSUE THREAD

**Issue by sin-en-2009** [jpmml/jpmml-evaluator#161]
The following error occurred while compiling the project
Error:(67, 36) java: 找不到符号
  符号:   类 ReportingFloatValue
  位置: 类 org.jpmml.evaluator.ReportingValueFactoryFactory.ReportingFloatValueFactory

**Comment by vruusmann** [comment]
Sorry, this error report does not contain any actionable information (at least for an english-speaking person)
