### ISSUE TITLE
ReportingValueFactoryFactory$ReportingFloatValue  can't compile

### ISSUE THREAD

**Issue by ranqiqiang** [jpmml/jpmml-evaluator#162]
Hello, when I enter class ReportingValueFactoryFactory,but can't  find ReportingFloatValue.

this code `return new ReportingFloatValue(0f, newReport(), null);`  can't compile !

Is not push?

**Comment by vruusmann** [comment]
Classes `org.jpmml.evaluator.ReportingDoubleValue` and `org.jpmml.evaluator.ReportingFloatValue` are generated during build by the `org.jpmml.evaluator.OperationProcessor` Java APT code generators.

> Is not push?

Both classes are part of the `org.jpmml:pmml-evaluator:${version}` distributable JAR file. Fix your classpath.

**Comment by ranqiqiang** [comment]
thanks ~.~

**Comment by MacleZhou** [comment]
Thank u
