### ISSUE TITLE
File input streams and evaluation calculations take too long

### ISSUE THREAD

**Issue by sin-en-2009** [jpmml/jpmml-evaluator#163]
I followed the case you provided to test, the code is as follows.But I found that loading the model as a file input stream was expensive, and the first time I used the evaluator method it was also expensive.**Is there any way to improve the speed of model loading?And what can be done to speed up the calculation of the first prediction?And how can I get the probability of a prediction as easily as using Python predict_prob?**

public class Test {
        public static Map lrHeartInputMap = new HashMap();
        public static  PMML pmml;
        static  String path = "D:/work/feiqiu/model.pmml";
        static  String  []  ss;
        static  ModelEvaluatorFactory modelEvaluatorFactory;
        static  ModelEvaluator<?> modelEvaluator;
        static  Evaluator evaluator;
        static List<InputField> inputFields;
        static{
		       try {
		        	    long begin = System.currentTimeMillis();
		        	    File file = new File(path);
				    InputStream inputStream = new FileInputStream(file);
				    pmml = org.jpmml.model.PMMLUtil.unmarshal(inputStream);
				    long end = System.currentTimeMillis();
				    System.out.println((end-begin)/1000+"s");
				     modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
				     modelEvaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
				     evaluator = (Evaluator) modelEvaluator;
				     inputFields = evaluator.getInputFields();
				} catch (Exception e) {
					e.printStackTrace();
				} 

                 }
         //Predictive core code
	public synchronized static void predictLrHeart() throws Exception {
	      try{
            	   Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();
		   long start = System.currentTimeMillis();
      	           for (InputField inputField : inputFields) {
      	            FieldName inputFieldName = inputField.getName();
      	            Object rawValue = lrHeartInputMap.get(inputFieldName.getValue());
      	            
      	            FieldValue inputFieldValue = inputField.prepare(rawValue); //error
      	            arguments.put(inputFieldName, inputFieldValue);
      	        }
		System.out.println("prepare time cost:"+(System.currentTimeMillis()-start));

		start = System.currentTimeMillis();
      	        Map<FieldName, ?> results = evaluator.evaluate(arguments);  //**time cost too long for first time**
		System.out.println("evaluate time cost:"+(System.currentTimeMillis()-start));
     	        List<TargetField> targetFields = evaluator.getTargetFields();
     }
    public static void main(String[] args) throws Exception {
		String kk [] ;
	    for(int i = 0;i<ss.length;i++){
			long start = System.currentTimeMillis();
	    	       kk = ss[i].split("\\|",-1);
	    	       lrHeartInputMap.clear();
	    	        lrHeartInputMap.put("user",kk[0]);
			lrHeartInputMap.put("pos", kk[1]);
			lrHeartInputMap.put("ad", kk[2]);
			lrHeartInputMap.put("time_stamp", kk[3]);
			lrHeartInputMap.put("page", kk[4]);
			lrHeartInputMap.put("network",kk[5]);
			lrHeartInputMap.put("category_c1", kk[6]);
			lrHeartInputMap.put("rating", kk[7]);
	        System.out.println("index="+i+" time cost:"+(System.currentTimeMillis()-start));
	        try{
	        	predictLrHeart();
	        }catch(Exception e){
	        	System.out.println("this is error");
	        }
	    }
	}
}

**Comment by vruusmann** [comment]
> The first time I used the evaluator method it was also expensive.

It's mentioned in the documentation, that the first evaluation is slower than all the following evaluations, because the evaluator does some cache-building and initialization at that time.

> And what can be done to speed up the calculation of the first prediction?

Embed some model verification data into the PMML document. In that case, the model verification takes care of evaluator warm-up, and all production evaluations will be constant speed.

> And how can I get the probability of a prediction as easily as using Python predict_prob?

If the PMML document contains a probabilistic classification model, then you get the estimated probability distribution by default. There's no need to invoke any extra methods.

In Python you must two function invocations - `predict(X)` and `predict_proba(X)` (and sometimes even the third `apply`). In PMML, you get all aspects of the prediction in a single `Evaluator#evaluate(Map)` invocation.
