### ISSUE TITLE
Question for installation

### ISSUE THREAD

**Issue by kwei94** [jpmml/jpmml-evaluator#167]
Hi, 

I am new to this field and I had read the installation guide. I had put the dependency under directory of myProject/app/build.gradle and there is no further step stated. Is there anything else I should do to access the library?Besides, where should put the pmml file which is exported from RapidMiner in Android Studio?

**Comment by vruusmann** [comment]
I don't see any (J)PMML related questions here.

For stuff like "How do I add a 3rd party library to my Android project" or "Where should I put resource files in my Android project", please refer to alternative questions/answer formats such as [StackOverflow](https://stackoverflow.com).
