### ISSUE TITLE
Can SVM PMML model return probability values？

### ISSUE THREAD

**Issue by linven0721** [jpmml/jpmml-evaluator#169]
Can SVM PMML model return probability values？

**Comment by vruusmann** [comment]
SVM classification models generally do not provide true probability distribution (this is a limitation of the SVM algorithm, not the PMML standard).

However, it is possible that a SVM PMML may provide fake/emulated probabilities. The JPMML+Evaluator library provides a method `org.jpmml.evaluator.ModelEvaluator#hasResultFeature(org.dmg.pmml.ResultFeature)` for querying model's functionality.

In the current case, you'd need to query for the `org.dmg.pmml.ResultFeature#PROBABILITY` enum constant:
```java
Evaluator evaluator = ...;
ModelEvaluator modelEvaluator = (ModelEvaluator)evaluator;
boolean probabilistic = modelEvaluator.hasResultFeature(ResultFeature.PROBABILITY);
```

Alternatively, you may iterate over output field declarations using the `org.jpmml.evaluator.Evaluator#getOutputFields()` method, and test if one or more of them correspond to the `ResultFeature#PROBABILITY` enum constant:
```java
Evaluator evaluator = ...;
List<OutputField> outputFields = evaluator.getOutputFields();
for(OutputField outputField : outputFields){
  boolean isProbability = (outputField.getField()).getResultFeature() == ResultFeature.PROBABILITY;
}
```

**Comment by Deepcong2019** [comment]
any result? @linven0721
