### ISSUE TITLE
Expose `org.jpmml.evaluator.tree.TreeModelEvaluator.Trail`

### ISSUE THREAD

**Issue by terusus** [jpmml/jpmml-evaluator#176]
The `org.jpmml.evaluator.tree.TreeModelEvaluator.Trail` is a `private` `static` class defined in `TreeModelEvaluator`. It does not implement any interfaces.

Perhaps you would want to expose this inner class since an instance of `Trail` is returned as a result of the evaluation done by a `TreeModelEvaluator`.

Or, please, explain how we are supposed to get results in that case?

**Comment by vruusmann** [comment]
> .. an instance of Trail is returned as a result of the evaluation done by a TreeModelEvaluator.

How is this even possible? Have you got an exception or something similar as a proof?

The main "entry point" is method `ModelEvaluator#evaluateInternal(EvaluationContext)`, which depending on the mining function type redirects to `TreeModelEvaluator#evaluateRegression(EvaluationContext)` or `#evaluateClassification(EvaluationContext)`. These two methods have `java.util.Map` as their return type, and I can't find any code paths that would lead to a situation where a `TreeModelEvaluator.Trail` instance is used either as a map key or value.

This class is an internal value object - it keeps track of a relevant portion (up to two node elements) of the traversed tree structure, plus some helper information (number of missing values handled). How is this information useful for an end user?

**Comment by terusus** [comment]
I am debugging the result returned from `evaluator.evaluate(...)`. The meaningful object that holds my result is of type `TreeModelEvaluator$2`. I cannot cast it to `Trail` but I can call the methods of `Trail` in the debug window.

How I got to this point? Copy/paste the first big example from [here](http://dmg.org/pmml/v4-3/TreeModel.html) (btw, this is referenced from the JPMML readme as well). And run the evaluation for `temperature=75, humidity=55, windy="false", outlook="overcast"`.

**Comment by vruusmann** [comment]
> The meaningful object within the maps that holds my result is of type TreeModelEvaluator$2

The referenced example is a classification-type decision tree model. To be more precise, it's a voting-type classification model (the prediction is given by the `Node@score` attribute), not a probability distribution-type classification model (the prediction is computed based on `ScoreDistribution` child elements).

Now, therefore, the the value of the target field is an anonymous subclass of `org.jpmml.evaluator.tree.NodeVote`: https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/tree/NodeVote.java

This particular object instance that you're seeing as `TreeModelEvaluator$2` is most likely instantiated here: https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/tree/TreeModelEvaluator.java#L341-L352

Now that we've identified the underlying class (ie. `NodeVote`), it's easy to see that it's "API" is defined by the abstract base class `org.jpmml.evaluator.Vote` and marker interfaces `o.j.e.HasEntityId`, `o.j.e.HasEntityRegistry` and `o.j.e.tree.HasDecisionPath`. I believe that the latter marker interesting is the most interesting for application users.

Try out the following code:
```java
Map<FieldName, ?> results = evaluator.evaluate(arguments);
Object targetValue = results.get(evaluator.getTargetField());
if(targetValue instanceof HasDecisionPath){
  HasDecisionPath hasDecisionPath = (HasDecisionPath)targetValue;
  // Prints a list of org.dmg.pmml.tree.Node objects, ordered hierarchically from the root to the winning leaf node
  System.out.println(hasDecisionPath.getDecisionPath());
}
```

**Comment by terusus** [comment]
Thank you @vruusmann. Indeed, it's an anonymous `NodeVote` instance.
