### ISSUE TITLE
Empty Classification

### ISSUE THREAD

**Issue by prachikhadke** [jpmml/jpmml-evaluator#177]
I am getting this exception for my code. But it's not clear why the exception is happening. The code was working fine before. I tried upgrading to latest version of library. Did not make a difference.

`org.jpmml.evaluator.EvaluationException: Empty classification
java.util.concurrent.ExecutionException: org.jpmml.evaluator.EvaluationException: Empty classification`

**Comment by vruusmann** [comment]
Really need to know more context to say anything useful.

What model type, what is the input data record, where exactly does the exception occur? Is it some JPMML-generated PMML document, or something else?

**Comment by prachikhadke** [comment]
It is a . JPPML generated PMML document. Model type is classification

**Comment by prachikhadke** [comment]
What I don't understand is - what does this Exception mean? There is no documentation about it in the repository. I found the lines where the exception is being thrown. Debugged it too. But not clear what it means by null entry? (https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/Classification.java#L70).

**Comment by vruusmann** [comment]
> It is a JPMML generated PMML document.

If so, then please use some toy dataset (Iris-Species, Audit-Adjusted) to manufacture a reproducible example.

**Comment by vruusmann** [comment]
> But not clear what it means by null entry?

If the classification is computed successfully (up to this point), then the `Classification$values` should be a non-empty `ValueMap` instance. In your case, it is empty, and therefore it's impossible to draw the winning entry out of it.

It definitely looks like an input data record problem.

**Comment by prachikhadke** [comment]
Ok. Will double check the input data. Thx. If it's a data issue, will close this ticket. Thx

**Comment by prachikhadke** [comment]
Ok. confirmed that it was a data issue. Going to close this ticket. Thx for the help @vruusmann .
