### ISSUE TITLE
I can not get the same result from pypmml

### ISSUE THREAD

**Issue by czh0318** [jpmml/jpmml-evaluator#178]
Hi, @vruusmann 
I could not get the same result from pypmml, my environment is:
**java version "1.8.0_191"
jpmml version 1.4.14
pmml version 4.3**
Could you please help me? Thank you.

Looking forward to your reply

**Comment by vruusmann** [comment]
> I could not get the same result from pypmml,

What is the difference? Some reproducible example?

In principle, you should be comparing JPMML-Evaluator predictions with the original framework (R, Scikit-Learn, Apache Spark).

If you need to evaluate PMML documents in Python, then please check out the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) library.

**Comment by czh0318** [comment]
> > I could not get the same result from pypmml,
> 
> What is the difference? Some reproducible example?
> 
> In principle, you should be comparing JPMML-Evaluator predictions with the original framework (R, Scikit-Learn, Apache Spark).
> 
> If you need to evaluate PMML documents in Python, then please check out the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) library.

Thank you for you reply, sir. 
I evaluate PMML documents in Java, and the pmml model is LightGBM. 
I can provide my pmml file and input param if necessary.

**Comment by czh0318** [comment]
> > I could not get the same result from pypmml,
> 
> What is the difference? Some reproducible example?
> 
> In principle, you should be comparing JPMML-Evaluator predictions with the original framework (R, Scikit-Learn, Apache Spark).
> 
> If you need to evaluate PMML documents in Python, then please check out the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) library.

Sir, the JPMML-Evaluator-Python library get the same result with jpmml-evaluator.

**Comment by vruusmann** [comment]
> I evaluate PMML documents in Java, and the pmml model is LightGBM.

The JPMML-Evaluator library has extensive integration tests for LightGBM available here: https://github.com/jpmml/jpmml-lightgbm/tree/master/src/test

Right now, I'm 99.87% confident that JPMML-Evaluator is giving you correct predictions, and PyPMML is giving you erroneous predictions. But I'm open to checking out your reproducible example(s) to remove all doubt about this remaining 0.13%.

You can your files to my e-mail which is listed on my profile.

**Comment by vruusmann** [comment]
> the JPMML-Evaluator-Python library get the same result with jpmml-evaluator.

This is expected, because as the name suggests, JPMML-Evaluator-Python is simply a thin Python wrapper around the JPMML-Evaluator library.

What are LightGBM predictions? Does JPMML-Evaluator(-Python) agree with those?

There's always a chance that you're making a typo when converting LightGBM models to PMML (for example, if the dataset is sparse, then the specification of missing values is invalid/incomplete). See the following tutorial about generating 100% valid PMML files: https://openscoring.io/blog/2019/04/07/converting_sklearn_lightgbm_pipeline_pmml/

**Comment by czh0318** [comment]
> > I evaluate PMML documents in Java, and the pmml model is LightGBM.
> 
> The JPMML-Evaluator library has extensive integration tests for LightGBM available here: https://github.com/jpmml/jpmml-lightgbm/tree/master/src/test
> 
> Right now, I'm 99.87% confident that JPMML-Evaluator is giving you correct predictions, and PyPMML is giving you erroneous predictions. But I'm open to checking out your reproducible example(s) to remove all doubt about this remaining 0.13%.
> 
> You can your files to my e-mail which is listed on my profile.

Sir, my files has been sent to you. Please check it. Thank you.

**Comment by czh0318** [comment]
> > > I evaluate PMML documents in Java, and the pmml model is LightGBM.
> > 
> > 
> > The JPMML-Evaluator library has extensive integration tests for LightGBM available here: https://github.com/jpmml/jpmml-lightgbm/tree/master/src/test
> > Right now, I'm 99.87% confident that JPMML-Evaluator is giving you correct predictions, and PyPMML is giving you erroneous predictions. But I'm open to checking out your reproducible example(s) to remove all doubt about this remaining 0.13%.
> > You can your files to my e-mail which is listed on my profile.
> 
> Sir, my files has been sent to you. Please check it. Thank you.

Sir, how about this issue, please.

**Comment by vruusmann** [comment]
@czh0318 Got your e-mail, but I can't really do anything useful with only one data record. I was expecting more data do that I could train a LightGBM model and compare its predictions against JPMML-Evaluator predictions.

Right now, I would assume that JPMML-Evaluator is giving you correct predictions (has extensive LightGBM test coverage), and PyPMML is giving you wrong predictions (has no LightGBM test coverage whatsoever). But there's this 0.13% chance that I might be wrong.

Anyway, I don't have time to debug third party PMML engines. If you think that JPMML-Evaluator is giving wrong predictions, then I'm expecting you to provide a very clear and reproducible test case about it.

**Comment by czh0318** [comment]
> @czh0318 Got your e-mail, but I can't really do anything useful with only one data record. I was expecting more data do that I could train a LightGBM model and compare its predictions against JPMML-Evaluator predictions.
> 
> Right now, I would assume that JPMML-Evaluator is giving you correct predictions (has extensive LightGBM test coverage), and PyPMML is giving you wrong predictions (has no LightGBM test coverage whatsoever). But there's this 0.13% chance that I might be wrong.
> 
> Anyway, I don't have time to debug third party PMML engines. If you think that JPMML-Evaluator is giving wrong predictions, then I'm expecting you to provide a very clear and reproducible test case about it.

Thank you, sir
