### ISSUE TITLE
Missed resources

### ISSUE THREAD

**Issue by MacleZhou** [jpmml/jpmml-evaluator#182]
In class ReportingValueFactoryFactory, which referenced but not able to find below files:

ReportingFloatValue, ReportingComplexFloatVector, ReportingSimpleFloatVector, ReportingDoubleValue, ReportingComplexDoubleVector, ReportingSimpleDoubleVector. 

Please help.

**Comment by vruusmann** [comment]
Exact duplicate of https://github.com/jpmml/jpmml-evaluator/issues/162
