### ISSUE TITLE
evaluator.evaluate is too slow for me

### ISSUE THREAD

**Issue by zepen** [jpmml/jpmml-evaluator#186]
Hi 大神 （This is what China calls a master ）
i have trainned a big model contain 110000 features, such as text features, categorical features and numeric features. First, i build a DataFrameMapper for features preprocesing and fit it. Second i use DataFrameMapper object transform features for SGDClassifier to fit. Final, i save a pipline by PMMLPipeline, That' s work well.  But When i  use model predict, it' s too slow!
Is this a reason that my model is too big? Have you any good idea for this?

That's my predict Test case

``` java
import org.dmg.pmml.FieldName;
import org.jpmml.evaluator.*;
import org.xml.sax.SAXException;
import javax.xml.bind.JAXBException;
import java.io.File;
import java.io.IOException;
import java.util.*;

public class TestL2R {

    //定义一个实用函数，就是python中的print函数，没别的意思
    private static void print(Object... args){
        Arrays.stream(args).forEach(System.out::print);
        System.out.println("");
    }


    public static void main(String [] args) throws JAXBException, SAXException, IOException {

        long start_time = System.currentTimeMillis();

        File file = new File("./target/classes/L2R.pmml");
        Evaluator evaluator = new LoadingModelEvaluatorBuilder().load(file).build();
        evaluator.verify();

        System.out.println("Load model Cost Time: " + (System.currentTimeMillis() - start_time) + " ms");

        long start_time2 = System.currentTimeMillis();

        // 模型入参
        Map<String, Object> map = new HashMap<>();
        map.put("type", 9.0);
        map.put("level", 0.0);
        map.put("recommend_num", 2.0);
        map.put("visits", 1.0);
        map.put("replies", 24.0);
        map.put("lights", 0.0);
        map.put("share_num", 0.0);
        map.put("fid", 112.0);
        map.put("post_num", 0.0);
        map.put("reply_num", 0.0);
        map.put("reply_light_num", 0.0);
        map.put("thread_rcmd_num", 0.0);
        map.put("news", 0.0);
        map.put("visit_time", 0.0);
        map.put("reply_time", 0.0);
        map.put("seg_query", "shaquille");
        map.put("seg_title", "【 拍卖 】   Shaquille   oneal   lakers   REP   40 码   截止 日期 时间   星期五   7月 25 日   23 . oo 的地位");
        map.put("topic_id", 54);

        System.out.println("Create Features Cost Time: " + (System.currentTimeMillis() - start_time2) + " ms");

        long start_time3 = System.currentTimeMillis();

        // 获取模型定义的特征
        List<? extends InputField> inputFields = evaluator.getInputFields();
        print("模型的特征是：", inputFields);
        // 获取模型定义的目标名称
        List<? extends TargetField> targetFields = evaluator.getTargetFields();
        print("目标字段是：",targetFields);

        Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();

        for(InputField inputField: inputFields){
            FieldName inputName = inputField.getName();
            String name = inputName.getValue();

            Object rawValue = map.get(name);
            FieldValue inputValue = inputField.prepare(rawValue);

            arguments.put(inputName, inputValue);
        }
        System.out.println("Get Features Cost Time: " + (System.currentTimeMillis() - start_time3) + " ms");

        long start_time4 = System.currentTimeMillis();

        Map<FieldName, ?> results = evaluator.evaluate(arguments);

        // 打印结果会更加了解其中的封装过程
        print("预测结果：");
        print(results);

        System.out.println("Predict calculate Cost Time: " + (System.currentTimeMillis() - start_time4) + " ms");

    }
}
```

macOs 10.14.6
CPU: 1.4 GHz Intel Core i5
JAVA jdk1.8.0_231

  <dependency>
        <groupId>org.jpmml</groupId>
        <artifactId>pmml-evaluator</artifactId>
        <version>1.4.13</version>
 </dependency>

Cost time:
![image](https://user-images.githubusercontent.com/18568380/79959045-31a48000-84b6-11ea-9cad-18304a839f22.png)

**Comment by vruusmann** [comment]
> i have trainned a big model contain 110000 features

You should probably introduce feature selection into your data science pipeline. Try reducing the number of features from 100k to 1000 (or 100), and the problem should be resolved.

Other than that, you may switch from PMML interpretation to PMML translation to Java bytecode: [JPMML-Transpiler](https://github.com/jpmml-transpiler)

**Comment by zepen** [comment]
I trainned is small model like iris_datasets, still cost 21 ms. But i use your provide LogisticRegressionIris.pmml only cost 0-1 ms. And i check what different bewteen two files.
You model files have ModelVerification block. So, Is this reason affect model performance？

**Comment by zepen** [comment]
=

> > i have trainned a big model contain 110000 features
> 
> You should probably introduce feature selection into your data science pipeline. Try reducing the number of features from 100k to 1000 (or 100), and the problem should be resolved.
> 
> Other than that, you may switch from PMML interpretation to PMML translation to Java bytecode: [JPMML-Transpiler](https://github.com/jpmml-transpiler)

I trainned is small model like iris_datasets, still cost 21 ms. But i use your provide LogisticRegressionIris.pmml only cost 0-1 ms. And i check what different bewteen two files.
You model files have ModelVerification block. So, Is this reason affect model performance？

**Comment by vruusmann** [comment]
> I trainned is small model like iris_datasets, still cost 21 ms.
> But i use your provide LogisticRegressionIris.pmml only cost 0-1 ms

The evaluation of the first data record is slower than the evaluation of all the subsequent data records, because there is some "warm up" work to do.

When performing model verification (eg. by invoking `Evaluator#verify()` with a non-empty verification dataset), then the "warm up" is handled there.

It's all explained in the README file.

**Comment by vruusmann** [comment]
When running performance tests, then you should score 1M data records to get a correct estimate (if your dataset is small, then simply run it in loop until you reach this 1M threshold).

**Comment by TPF2017** [comment]
> =
> 
> > > i have trainned a big model contain 110000 features
> > 
> > 
> > You should probably introduce feature selection into your data science pipeline. Try reducing the number of features from 100k to 1000 (or 100), and the problem should be resolved.
> > Other than that, you may switch from PMML interpretation to PMML translation to Java bytecode: [JPMML-Transpiler](https://github.com/jpmml-transpiler)
> 
> I trainned is small model like iris_datasets, still cost 21 ms. But i use your provide LogisticRegressionIris.pmml only cost 0-1 ms. And i check what different bewteen two files.
> You model files have ModelVerification block. So, Is this reason affect model performance？

老哥。问题解决了吗，我LightGBM训练了一个模型，预测一次要20ms+，并不是warmup的问题。

**Comment by zepen** [comment]
> > =
> > > > i have trainned a big model contain 110000 features
> > > 
> > > 
> > > You should probably introduce feature selection into your data science pipeline. Try reducing the number of features from 100k to 1000 (or 100), and the problem should be resolved.
> > > Other than that, you may switch from PMML interpretation to PMML translation to Java bytecode: [JPMML-Transpiler](https://github.com/jpmml-transpiler)
> > 
> > 
> > I trainned is small model like iris_datasets, still cost 21 ms. But i use your provide LogisticRegressionIris.pmml only cost 0-1 ms. And i check what different bewteen two files.
> > You model files have ModelVerification block. So, Is this reason affect model performance？
> 
> 老哥。问题解决了吗，我LightGBM训练了一个模型，预测一次要20ms+，并不是warmup的问题。

我放弃这个方案，改用手写特征转换。
