### ISSUE TITLE
Slow KNN evaluation

### ISSUE THREAD

**Issue by yangguang760** [jpmml/jpmml-evaluator#187]
Hi,
I have tried a KNN regression for n_neighbors=90 and n_features=30, it was very slow compared with scikitlearn.
Since README tells 'The processing of the first data record will be significantly slower than the processing of all subsequent data records', I have profiled my process excluding first several evaluations.
Is it possible to accelerate this process? Thx.
Profile results are as followings:
![捕获6](https://user-images.githubusercontent.com/748502/80476033-61eb9300-897c-11ea-8947-771c3ff22799.JPG)

**Comment by yangguang760** [comment]
update:
when use jpmml-transpiler to gen jar from pmml, 
```
error: code too large
```
raised.

**Comment by vruusmann** [comment]
> I have tried a KNN regression for n_neighbors=90 and n_features=30

The performance of KNN mostly depends on the number of "training instances" (what was the number of data records in the training dataset).

> It was very slow compared with scikitlearn.

That is to be expected - PMML is not competing with Scikit-Learn in terms of speed (but in terms of model maintainability, ease of use, explainability etc.).

If performance is critical for your use case then stay 100% in Scikit-Learn realm.

**Comment by yangguang760** [comment]
@vruusmann 
Thanks for your kindly explanation.
