### ISSUE TITLE
For JPMML-Android 's pmml model loading question 

### ISSUE THREAD

**Issue by momo1986** [jpmml/jpmml-evaluator#189]
Hello, I have the model in the format of jpmml, e.g., random_forest.pmml.

Is it possible to load it directly  rather than to transfer it to ser-format model as described in this archive?

https://github.com/jpmml/jpmml-android

Hello， @vruusmann .

Could you comment on this?

Thanks & Regards!
Momo

**Comment by vruusmann** [comment]
> Is it possible to load it directly ..

The last time I checked (more than a year ago), Android didn't support unmarshalling XML files into POJOs using the JAXB framework.

Perhaps it's possible now. I don't know/don't have time to experiment with it.

> .. rather than to transfer it to ser-format model as described in this archive?

The objective is to transfer a POJO (a class model object rooted at `org.dmg.pmml.PMML`) from PC to android.

These are the two options:

1. Transfer using Java serialization mechanism as a SER file (ie. write out in PC using `java.io.ObjectOutputStream`, read back in Android using `java.io.ObjectInputStream`). You can do it manually. The PMML-SER plugin (in the JPMML-Model project) was there simply for convenience.

2. Transpiler the PMML file to a JAR file using the [JPMML-Transpiler](https://github.com/jpmml/jpmml-transpiler) library/command-line application. The transpilation works for all PMML files. However, for some PMML files (eg. decision tree ensembles), it will be possible to generate an optimized version.

I'd personally go with the second option (transpilation) today.
