### ISSUE TITLE
Issue with optype="continuous" using PMML 3.2

### ISSUE THREAD

**Issue by Almost9000** [jpmml/jpmml-evaluator#199]
Hello.
When using the DMG PMML example:
http://dmg.org/pmml/pmml_examples/rattle_pmml_examples/AuditBinaryReg.xml

The loaded PMML fails during runtime saying "Element RegressionModel is not valid":
org.jpmml.evaluator.InvalidElementException (at or around line 70 of the PMML document): Element RegressionModel is not valid
at org.jpmml.evaluator.regression.RegressionModelEvaluator.evaluateClassification(RegressionModelEvaluator.java:136)
at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:535)
at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:503)
at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)

Correcting optype:
From 
<DataField name="TARGET_Adjusted" optype="continuous" dataType="double"/>
 
To 
<DataField name="TARGET_Adjusted" optype="categorical" dataType="string"/>

The issue is resolved, however since the example is from the official DMG website it would be expected that no additional corrections are required for the PMML to run without issues.

Any input regarding this would be most welcome.

Thank you.

**Comment by vruusmann** [comment]
> When using the DMG PMML example:
> http://dmg.org/pmml/pmml_examples/rattle_pmml_examples/AuditBinaryReg.xml

This is a classification model. The target field of a classification model must have a discrete optype (one of `categorical` or `ordinal`).

Sure, the data type of a classification model can be `double`, but it should be a discrete double then (this model has two possible output values - `0` and `1`). A `continuous` optype would suggest that the model may also predict `0.63317` or some other real value.

> the example is from the official DMG website 
> it would be expected that no additional corrections 
> are required for the PMML to run without issues.

As explained in another issue (https://github.com/jpmml/jpmml-evaluator/issues/200#issuecomment-661324681), the examples section of the DMG.org website is full of invalid/incorrect PMML documents.

This particular PMML document has been generated in 2012 by the [legacy `pmml` package](https://CRAN.R-project.org/package=pmml).

This R package is not known for its quality and adherence to the PMML standard.

**Comment by vruusmann** [comment]
To clarify, this exception is a sanity check, which is supposed to guard against deploying obviously invalid/incorrect PMML documents into production.

What be the expected change? Do you want a configuration option to disable sanity checks? Would prefer to receive bad predictions, and debug them one by one?

**Comment by alexeidukaitis** [comment]
Hello @vruusmann 
The key concern was that the official DMG examples are not working without making additional corrections.
Thank you for the explanation. I believe that this answer my question.
Thank you very much.
