### ISSUE TITLE
Getting wrong results for myata using svm pmml model

### ISSUE THREAD

**Issue by kltr8** [jpmml/jpmml-evaluator#20]
Hi,
Using jpmml evaluator for SVM pmml model execution for Audit data set working fine , But for user data getting wrong results. Actually the data set  having 4 fields in that one is target field,contains three categories.
I have used below line for execution in my console.

java -cp target/example-1.2-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model model.pmml --input input.tsv --output output.tsv

Please help me on the above mention query.
Thanks in advance...

**Comment by vruusmann** [comment]
> But for user data getting wrong results. 

That's not informative at all.

Please supply your `model.pmml` and `input.tsv` files, together with an "expected correct results" file.

Given that the SVM evaluation part has full test coverage for R/Scikit-Learn/KNIME etc., then I have a reason to believe that your PMML file is broken, not the JPMML-Evaluator library.

**Comment by kltr8** [comment]
Thank you for the reply.
Please find the attached zip contains model.pmml, input.csv and "expected correct results".
FYI I have generated model pmml using R.
[sample.zip](https://github.com/jpmml/jpmml-evaluator/files/173577/sample.zip)

And one more information  required we are planning to execute Timeseries pmml model can you please share that when will the jpmml evaluator will support.

Thanks in advance.

**Comment by vruusmann** [comment]
There appears to be a problem with the labeling of predictions. For example, R class labels "1", "2" and "3" correspond to JPMML class labels "3", "1" and "2", respectively.

JPMML-Evaluator includes integration tests for R/Rattle LibSVM models (both for binary- and multi-class classification cases), which all pass cleanly. 

So, I think there's a problem with your R script. For example, it could be the case that R is treating your target variable "x4" as a **integer**, but it should be treated as **factor**. Please verify the data type of your target column, eg. via `class(df$x4)`. Also, you might try re-labeling target categories as "one", "two" and "three" and re-run your workflow again.

**Comment by kltr8** [comment]
Thanks for the reply.
I have considered target variable as categorical only not integer.
Actually i am using labeling columns as string types only still i am getting same issue.
please find the below line code in model pmml as consider categorical only.

<DataField name="x4_target" optype="categorical" dataType="string"/>

Thanks in advance.

**Comment by vruusmann** [comment]
Then perhaps you should convert the target variable `x4` from **string** data type to **factor** data type.

The problem is definitely related to your R script and/or `pmml` package, not JPMML-Evaluator library, because the `DataField` element does not specify any target categories at all.

Currently it looks like this:
```
<DataField name="x4_target" optype="categorical" dataType="string"/>
```

But it should look something like this:
```
<DataField name="x4_target" optype="categorical" dataType="string">
  <Value value="1"/>
  <Value value="2"/>
  <Value value="3"/>
</DataField>
```

**Comment by kltr8** [comment]
As per your above inputs, we have generated PMML file but output is not coming as per desire output.

PMML snippet

<DataDictionary numberOfFields="7">
  <DataField name="Cluster" optype="categorical" dataType="string">
   <Value value="1"/>
   <Value value="2"/>
   <Value value="3"/>
  </DataField>
  <DataField name="accelerator_pedal_position" optype="continuous" dataType="double"/>
  <DataField name="engine_speed_Trns" optype="continuous" dataType="double"/>
  <DataField name="fuel_consumed" optype="continuous" dataType="double"/>
  <DataField name="fuel_level" optype="continuous" dataType="double"/>
  <DataField name="torque_at_transmission" optype="continuous" dataType="double"/>
  <DataField name="vehicle_speed" optype="continuous" dataType="double"/>
 </DataDictionary>

output file: We are getting output(Predicted_Cluster) as 1->1 and for 2->3 and 3->2.

Please suggest on the above mention.
