### ISSUE TITLE
Required attribute Node@score is not defined error

### ISSUE THREAD

**Issue by rahuls04** [jpmml/jpmml-evaluator#201]
I am trying to move from a logistic regression model to xgboost. However, when I run my test cases on my new xgboost PMML I get the following error - `org.jpmml.evaluator.MissingAttributeException: Required attribute Node@score is not defined` 

Possible solutions?

**Comment by vruusmann** [comment]
> Required attribute Node@score is not defined
> 
> Possible solutions?

Perhaps you should add Node@score attributes to all terminal (aka leaf) Node elements?

Where did you get this XGBoost PMML file? Was it generated using JPMML-XGBoost?

**Comment by rahuls04** [comment]
The xgboost pmml file was generated using the R pmml package

**Comment by rahuls04** [comment]
I do have Node score attributes at my leaf nodes like so - 
![image](https://user-images.githubusercontent.com/51176319/88225584-968b8580-cc1f-11ea-9e20-a83c26a56972.png)

**Comment by vruusmann** [comment]
> The xgboost pmml file was generated using the R pmml package

It's probably incorrect/invalid then.

According to the PMML specification, the Node@score attribute is required. 

Quoting http://dmg.org/pmml/v4-3/TreeModel.html: "it is the model provider's responsibility to make sure that it is not possible that the scoring process ends in a Node which does not have a score attribute. This includes scenarios with missing values where the final Node is not necessarily a leaf node."

**Comment by vruusmann** [comment]
> The xgboost pmml file was generated using the R pmml package

Please re-export your xgboost model using the [R2PMML](https://github.com/jpmml/r2pmml) package. The generated PMML file will be about 50% smaller, and correct.

**Comment by rahuls04** [comment]
Does the R2pmml package support complex feature transforms?

**Comment by vruusmann** [comment]
> Does the R2pmml package support complex feature transforms?

Depends.

But what good are those complex feature transforms of the R `pmml` package, if the final model is incorrectly encoded?
