### ISSUE TITLE
how to set the param model's value in method 'newModelEvaluator(PMML pmml, Model model)'

### ISSUE THREAD

**Issue by yuzhixing** [jpmml/jpmml-evaluator#206]
1. i have trans lightgbm.txt to lightgbm.pmml
2. i have readed lightgbm.pmml to memory by PMMLUtil.unmarshal(InputStream is)
3. i want use ModelEvaluator to supply predict service, but how to set param model?
Method: 
ModelEvaluatorFactory::newModelEvaluator(PMML pmml, Model model)

here is the full code:

public static void predictLrHeart(Map<String, Object> irismap, String pathxml) throws Exception {
        PMML pmml;
        File file = new File(pathxml);
        InputStream inputStream = new FileInputStream(file);
        try (InputStream is = inputStream) {
            //loading model
            pmml = org.jpmml.model.PMMLUtil.unmarshal(is);

            //build evaluator
            ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory
                    .newInstance();
            ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory
                    .newModelEvaluator(pmml);
            Evaluator evaluator = (Evaluator) modelEvaluator;
            
            //set feature value
            List<InputField> inputFields = evaluator.getActiveFields();
            Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();
            for (InputField inputField : inputFields) {
                FieldName inputFieldName = inputField.getName();
                Object rawValue = irismap
                        .get(inputFieldName.getValue());
                FieldValue inputFieldValue = inputField.prepare(rawValue);
                arguments.put(inputFieldName, inputFieldValue);
            }
            
            // exe
            Map<FieldName, ?> results = evaluator.evaluate(arguments);

            //get result
            List<TargetField> targetFields = evaluator.getTargetFields();
            for (TargetField targetField : targetFields) {
                FieldName targetFieldName = targetField.getName();
                Object targetFieldValue = results.get(targetFieldName);
                System.err.println("target: " + targetFieldName.getValue()
                        + " value: " + targetFieldValue);
            }
        } catch (Exception e) {
            System.out.println("error");
        }
    }

**Comment by vruusmann** [comment]
See https://github.com/jpmml/jpmml-evaluator#basic-usage

**Comment by yuzhixing** [comment]
nice， it works
