### ISSUE TITLE
DuplicateValueException error return when running evaluator

### ISSUE THREAD

**Issue by yuzhixing** [jpmml/jpmml-evaluator#208]
the full error - 
"org.jpmml.evaluator.DuplicateValueException: The value for field "probability_1016129886568,1321543839397,1954369517115,2102497214357,3770976506908,3985026501481,4065859085409,4548736298713,4928117448130,5513081875434,5630062527708,5682840599725,5881149506266,6040443769356,6070958200281,7067516232960,7615243794757,8142179536886,8276163626789,8327095443768,8921305085109" has already been defined"

what's wrong with it!

**Comment by vruusmann** [comment]
The PMML file is invalid - it attempts to re-assign a field value.

Judging by the file name pattern (`probability_*`), it looks to me that this PMML file has not been generated by JPMML conversion tools.

You should identify the author of the conversion tool, and report this issue to him/her. This is not my business.

**Comment by yuzhixing** [comment]
I feed this problem back to the algorithmic students！thanks！
