### ISSUE TITLE
How to improve prediction performance

### ISSUE THREAD

**Issue by yuzhixing** [jpmml/jpmml-evaluator#209]
a candidate will cost 35ms to predict by lightgbm model loadeb by org.jpmml.evaluator。
and one request will send 5000 candidate  to predict，then it will cost 2~3minutes by one thread!
Although increase the number of threads can improve performance, but it is CPU intensive request, qps will be limited！
so it can't provide online services！
can you get some suggest about improve prediction performance！

code ：
```
// prepare feature
Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();
	for (InputField inputField : evaluator.getInputFields()) {
		FieldName inputName = inputField.getName();

		Object rawValue = inputFtMap.get(inputName.getValue());
		arguments.put(inputName, inputField.prepare(rawValue));
}

// model predict
Map<FieldName, ?> results = evaluator.evaluate(arguments);
```
it (evaluator.evaluate) will cost 35ms, and one request will predict 5000 candicate.

thank you， please give some advice。

**Comment by vruusmann** [comment]
There's something wrong with your setup - it should take approximately 35 **micro**seconds to make a single prediction, not 35 **milli**seconds.

I can't be any more specific unless I have a full technical description of 1) your model, and 2) how it's being loaded. Right now you're copy&pasting irrelevant code from the README file.

> so it can't provide online services！

Why should I care?

**Comment by vruusmann** [comment]
Have you tried the [JPMML-Transpiler](https://github.com/jpmml/jpmml-transpiler) approach?

**Comment by yuzhixing** [comment]
OK，thanks。 it takes 35 milliseconds，not 35 microseconds， so i should improve prediction performance。
