### ISSUE TITLE
JPMML Compilation Error

### ISSUE THREAD

**Issue by vmuraliraju** [jpmml/jpmml-evaluator#21]
Description - Duplicate methods named spliterator with the parameters () and () are inherited from the types Collection<E> and Iterable<E>SparseArrayUtil.java	/pmml- evaluator/src/
main/java/org/jpmml/evaluator	

While compiling the project eclipse, I am getting above error. Have downloaded latest code yesterday.

**Comment by vruusmann** [comment]
Please set up your Eclipse IDE project properly.
