### ISSUE TITLE
Improve (binary-) compatibility with older Android versions

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-evaluator#210]
See https://github.com/jpmml/jpmml-model/issues/27#issuecomment-745114346

**Comment by atlantis0** [comment]
Okay, here is the stack trace on Android 7

`E  Process: com.custom.model, PID: 20018
E  java.lang.NoSuchMethodError: No virtual method getParameters()[Ljava/lang/reflect/Parameter; in class Ljava/lang/reflect/Constructor; or its super classes (declaration o
f 'java.lang.reflect.Constructor' appears in /system/framework/core-oj.jar)
E      at org.jpmml.evaluator.ModelManagerFactory.findConstructor(ModelManagerFactory.java:251)
E      at org.jpmml.evaluator.ModelManagerFactory.newModelManager(ModelManagerFactory.java:97)
E      at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:38)
E      at org.jpmml.evaluator.ModelEvaluatorBuilder.build(ModelEvaluatorBuilder.java:115)
E      at com.custom.model.sdk.PMMLBuilder.build(PMMLBuilder.java:32)`

**Comment by vruusmann** [comment]
The stack trace suggests that the Android version of JDK8 does not provide the `java.lang.Constructor#getParameters()` method.

JPMML-Evaluator 1.5.X uses reflection to choose the most appropriate model evaluator subclass for some model element. Nothing too crazy (in terms of what reflection can do), and it works on all desktop JDK8 versions - see https://github.com/jpmml/jpmml-evaluator/actions?query=workflow%3Amaven (full compatibility with all JDK versions in 8 .. 14 range)

**Comment by vruusmann** [comment]
@atlantis0 What is my best option for running the Apache Maven build in a Android-compatible manner? Basically, I'd like to enhance the current GitHub Actions CI configuration with some Android runtimes. Can it be done?

**Comment by vruusmann** [comment]
In principle, I could use name-based matching instead of reflection here.

Now: use reflection to find out the bounds of the `ModelEvaluator<Model>` subclass (`class TreeModelEvaluator extends ModelEvaluator<TreeModel>`).

In the future: use rflection first, but if that fails, try again with simple class name matching approach. There's already a convention in place that the name of a `ModelEvaluator<Model>` subclass follows a pattern `org.jpmml.evaluator.<Model.toLowerCase()>.<Prefix><Model>Evaluator`.

**Comment by atlantis0** [comment]
> @atlantis0 What is my best option for running the Apache Maven build in a Android-compatible manner? Basically, I'd like to enhance the current GitHub Actions CI configuration with some Android runtimes. Can it be done?

I am not aware of any. I usually build Android-based projects using gradle.

**Comment by vruusmann** [comment]
> I usually build Android-based projects using gradle.

My question could be rephrased as - "how do I customize the runtime Java API version for a CI run". The Apache Maven build would be run using JDK8 as usual, but I'd like to switch the standard JRE JAR with different Android version JARs (aka library matrix) for running the unit tests.

I'd like to be informed by the CI system automatically when I'm about to introduce some Android-incompatible API.

**Comment by vruusmann** [comment]
Let's go by trial and error first.

I'll simplify/downgrade reflection operations, and you report back to me if it works.

What's the minimum Android API version?

**Comment by atlantis0** [comment]
Android 5.0. API level 21

**Comment by vruusmann** [comment]
@atlantis0 Can you check if the `HEAD` version works (replace JPMML-Evaluator version 1.5.7 with 1.5-SNAPSHOT).

If there's a new technical problem, please re-open this issue.

**Comment by atlantis0** [comment]
@vruusmann Got `HEAD` working on Android 7 :) Can you publish this version on maven central?

**Comment by vruusmann** [comment]
> Got HEAD working on Android 7 :)

@atlantis0 But what about Android 5, which was your original target?

> Can you publish this version on maven central?

The codebase hasn't accumulated enough changes to merit a new release yet. I'd like to work on current open matters (my internal TODO list) over this coming weekend.

There should be a new release out by next Monday (21st of December, 2020) though.

**Comment by atlantis0** [comment]
Got my hands on an Android 5 device. Looks like the following method is not available on Android 5 & 6. https://developer.android.com/reference/java/util/Arrays#stream(int[]). Hence the current compatibility stops at Android 7. See crash stack trace below

`                         E  Process: com.master.jpmml, PID: 2755
                         E  java.lang.NoSuchMethodError: No static method stream([Ljava/lang/Object;)Ljava/util/stream/Stream; in class Ljava/util/Arrays; or its su
                            per classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar)
                         E      at org.jpmml.evaluator.ResourceUtil.readFieldNames(ResourceUtil.java:41)
                         E      at com.custom.model.sdk.BetterPMML.<clinit>(BetterPMML.java:52)
                         E      at com.master.jpmml.PMMLBuilder.build(PMMLBuilder.java:20)`

**Comment by vruusmann** [comment]
@atlantis0 Can you check out the `HEAD` version again, and re-run your experiment on Android 5.

I expect that you should be able to construct the `org.dmg.pmml.PMML` subclass now. However, can you execute it (in transpiled mode-) with the JPMML-Evaluator library?

If Android 5 can do basic JDK8 streams and lambdas, then the experiment might succeed.

**Comment by atlantis0** [comment]
Just checked on Android 5. See another crash below. It seems this method is only found in Android 7 and above. https://developer.android.com/reference/java/util/Map?hl=en#putIfAbsent(K,%20V)

`java.lang.NoSuchMethodError: No interface method putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super c
                            lasses (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)
                         E      at org.dmg.pmml.FieldName.create(FieldName.java:98)
                         E      at org.jpmml.evaluator.ResourceUtil.readFieldNames(ResourceUtil.java:46)`

**Comment by vruusmann** [comment]
The method `#putIfAbsent(Object, Object)` is indicative of concurrent access. It was introduced by `java.util.concurrent.ConcurrentMap` in Java 1.5, but was "back-ported" to `java.util.Map` in Java 1.8.

Speaking about the `org.dmg.pmml.FieldName#CACHE` class constant, then `java.util.concurrent.ConcurrentMap` is a much more appropriate field type there than the `java.util.Map` was. After all, this is a global cache, which may be queried/modified by any number of application threads at a time.

**Comment by vruusmann** [comment]
@atlantis0 Let's aim for a two-stage solution here. There will be an Android 7 compatible release on Monday, but let's keep exploring the options to get down to Android 5 level after that.

As a first step, I pushed a commit to the JPMML-Model repository that got rid of the `Map#putIfAbsent(Object, Object)` method call there.

There's only a ingle use of `Map#putIfAbsent(..)` in the JPMML-Evaluator codebase, but it's located inside the `org.jpmml.evaluator.EvaluationContext` class, which is rather important from the performance perspective:
https://github.com/jpmml/jpmml-evaluator/blob/1.5.7/pmml-evaluator/src/main/java/org/jpmml/evaluator/EvaluationContext.java#L137

Can you do the following to help figure out next steps on Android 7 -> 5 migration path:
1. Check out the `HEAD` version of the JPMML-Model library, and build it into a `1.5-SNAPSHOT` version locally.
2. Check out the `HEAD` version of the JPMML-Evaluator library, and replace the highlighted `Map#putIfAbsent(..)` method invocation with plain `Map#put(Object, Object)` invocation. Then, edit the `/pom.xml` file (the one in the root directory) and bump all JPMML-Model dependency versions from `1.5.8` to `1.5-SNAPSHOT` (so that the above changes took effect). Build everything into a `1.5-SNAPSHOT` version locally.
3. Attach this modified JPMML-Evaluator to your application, and re-run on Android 5. What breaks next?

For your convenience, I've added a patchfile `NoPutIfAbsent.patch` that summarizes the changed needed in the second point.
[NoPutIfAbsent.patch.txt](https://github.com/jpmml/jpmml-evaluator/files/5718004/NoPutIfAbsent.patch.txt)

**Comment by atlantis0** [comment]
@vruusmann Thank you for the detailed instruction. I was able to build `HEAD` on both repos and here is the output. 

`                         E  Process: com.master.jpmml, PID: 3808
                         E  java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/util/function/ToIntFunction;
                         E      at com.custom.sdk.BetterPMML$JavaModel$202125197.<clinit>(BetterPMML.java:770)
                         E      at com.custom.sdk.BetterPMML.ensureLoaded(BetterPMML.java:66)
                         E      at com.custom.sdk.BetterPMML.<clinit>(BetterPMML.java:57)`

Looks like, https://developer.android.com/reference/java/util/function/ToIntFunction?hl=en is not available on Android 5 & 6. One more thing, tests were failing on `jpmml-evaluator` repo. I had to skip it to get a successful build.

**Comment by vruusmann** [comment]
> One more thing, tests were failing on jpmml-evaluator repo. I had to skip it to get a successful build.

@atlantis0 When I apply the `NoPutIfAbsent.patch(.txt)` to the `HEAD` version, then the Apache Maven build succeeds (with all unit tests being executed).

Do you have the logfile of a failed build available? If you do, please attach it here so that I could see what's going on.

**Comment by vruusmann** [comment]
> Looks like, https://developer.android.com/reference/java/util/function/ToIntFunction?hl=en is not available on Android 5 & 6. 

The JPMML-Transpiler library needs to use a functional interface that returns a primitive `int`. The `java.util.function.ToIntFunction` was readily available, so I didn't bother to define a new one.

However, if needed, it can be done.

**Comment by vruusmann** [comment]
@atlantis0 It's possible to perform Android API checks using the [Animal Sniffer Maven Plugin](https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/):
https://github.com/jpmml/jpmml-evaluator/blob/1.5.8/pom.xml#L267-L305

I'm currently performing two checks:

First, the check against Android 8.0 (API level 26) and newer passes cleanly:
https://github.com/jpmml/jpmml-evaluator/blob/1.5.8/pom.xml#L272-L285

Second, the check against Android 7.0 and 7.1 (API levels 24 and 25) passes when all date/time/datetime-related functionality is ignored:
https://github.com/jpmml/jpmml-evaluator/blob/1.5.8/pom.xml#L286-L303

You can experiment with earlier Android versions by declaring another `<execution>` element, and specifying the desired signature dependency. My experiments with Adroid 6.0 (API level 23) indicates very many difficult-to-correct API compatibilities (mostly related to Java streaming API).

I'll set up a similar check for JPMML-Model and JPMML-Transpiler projects, and try to skew them toward earlier Android API versions. The transpiled code can bypass blocking JPMML-Evaluator methods if necessary.

**Comment by vruusmann** [comment]
I've did some major refactoring over the holiday season, and now I've come to a point where both JPMML-Model and JPMML-Evaluator libraries should be both Android 5.0 compatible (except for the date/time/datetime functionality):

- JPMML-Model 1.5.11 and newer
- JPMML-Evaluator 1.5.11 and newer

I'm yet to figure out if the missing `java.time.*` classes pose a problem for some JPMML-Evaluator utility methods or not. For example, the `org.jpmml.evaluator.TypeUtil#toInteger(Object)` utility methods performs some instanceof checks against `java.time.*` temporal types. If this method cannot be loaded and defined by the JVM because of that, then probably a good deal of integer functionality is also unavailable.

Will explore deeper in the next iteration. It should be possible to split big utility methods into smaller ones so that a few missing `java.time.*` classes wouldn't cause so much trouble.
