### ISSUE TITLE
single column input CSV into EvaluationExample results in IllegalArgumentException

### ISSUE THREAD

**Issue by amoldavsky** [jpmml/jpmml-evaluator#212]
If you supply a CSV with a single column as input you will get an `IllegalArgumentException`.

example repo:
https://github.com/amoldavsky/jpmml-tfodf-SGDClassifier-bug/tree/csv-single-column-bug

```bash
> ./jpmml-test.sh
Exception in thread "main" java.lang.IllegalArgumentException
        at org.jpmml.evaluator.testing.CsvUtil.getSeparator(CsvUtil.java:108)
        at org.jpmml.evaluator.testing.CsvUtil.readTable(CsvUtil.java:60)
        at org.jpmml.evaluator.example.Example.readTable(Example.java:129)
        at org.jpmml.evaluator.example.EvaluationExample.execute(EvaluationExample.java:274)
        at org.jpmml.evaluator.example.Example.execute(Example.java:92)
        at org.jpmml.evaluator.example.EvaluationExample.main(EvaluationExample.java:262)
```

**Comment by vruusmann** [comment]
The CSV parser component is trying to detect the separator character automatically. It does so by probing some common characters and observing if it finds >1 of them.

Obviously, this test fails if there's **less than two** columns in the CSV file.

In such a situation you should be supplying the value of the separator char manually using the `--separator` command-line option.

In case of a single-column CSV file you should specify a rare/nonsensical character as the separator. For example, the tab character `--separator "\\t"` is often a good candidate.

I don't see an elegant fix for this issue, hence resolving/labelling it as "won't fix". In your own real application (my example applications are just toys) you should be using a proper CSV parser library, and see what kind of separator detection functionality is available there.

**Comment by amoldavsky** [comment]
Right, I agree with your assessment for real-life applications, though, keep in mind that people like me will be running your examples with the toy application jar you provided using with their own test data and run into this case while evaluating. It might be a good idea to possibly document that or if in code you can check for commas and if non found default to "\t" as the separator... This is something only for you to weight and decide.

P.S.
In real-life applications I personally do not even consider CSV as an option. Pretty much everything ends up being an API call either as Rest or gRPC. In either way, the input almost always ends being JSON these days, which is my case as well so I agree with your assessment for real-file applications.
