### ISSUE TITLE
evaluate is slow at first invoke

### ISSUE THREAD

**Issue by liumy601** [jpmml/jpmml-evaluator#214]
Hey, i just found when i invoke evaluator.evaluate(arguments) at first time, it takes about 100ms, but from second times, it's very fast and takes nearly about 1ms. I'm curious about this, can you please give me some clarifications?

**Comment by vruusmann** [comment]
> when i invoke evaluator.evaluate(arguments) at first time, it takes about 100ms, but from second times, it's very fast and takes nearly about 1ms

It's explained by lazy initialization - the model evaluator is performing some internal parsing/cache building (when using some PMML markup fragment for the first time).

In case of decision tree (-ensemble) models, it's probably mostly about indexing `Node` elements..

However, the lazy initialization was greatly reduced in https://github.com/jpmml/jpmml-evaluator/commit/c2c4ece502fe8e754cb111bbddae57310807954e

If you're still seeing a 100x effect between the first and second scoring, then you're probably using an outdated JPMML-Evaluator version.

> can you please give me some clarifications?

The effect can be moved away from the main loop by "pre-warming" the model evaluator using the model verification mechanism

This has been explained countless times over the past 5+ years - use the search.
