### ISSUE TITLE
Utilizing Regex in PMML

### ISSUE THREAD

**Issue by axemixer** [jpmml/jpmml-evaluator#215]
Is it possible that adding replace function with regex in PMML?  If so , Do you have such an example ? I've done some research online but could not find anything about that.

Thanks

**Comment by vruusmann** [comment]
> Is it possible that adding replace function with regex in PMML?

See http://dmg.org/pmml/v4-4-1/BuiltinFunctions.html#replace

> Do you have such an example ?

**Scikit-Learn** - implemented as the `sklearn2pmml.preprocessing.ReplaceTransformer` transformer class: https://github.com/jpmml/sklearn2pmml/blob/0.66.1/sklearn2pmml/preprocessing/__init__.py#L318-L333

Examples:
https://github.com/jpmml/sklearn2pmml/blob/0.66.1/sklearn2pmml/preprocessing/tests/__init__.py#L387-L392
https://github.com/jpmml/jpmml-sklearn/blob/1.6.11/src/test/resources/main.py#L132

**Apache Spark ML** - implemented as the [`regexp_replace`](https://spark.apache.org/docs/2.4.0/api/sql/index.html#regexp_replace) SQL function via the `org.apache.spark.ml.feature.SQLTransformer` transformer class.

Examples:
https://github.com/jpmml/jpmml-sparkml/blob/1.5.11/src/test/java/org/jpmml/sparkml/ExpressionTranslatorTest.java#L195-L209
