### ISSUE TITLE
Getting wrong svm model result 

### ISSUE THREAD

**Issue by kltr8** [jpmml/jpmml-evaluator#22]
https://github.com/jpmml/jpmml-evaluator/issues/20

As per your inputs on above url , we have generated PMML file but output is not coming as per desire output.

PMML snippet:

<DataDictionary numberOfFields="7">
  <DataField name="Cluster" optype="categorical" dataType="string">
   <Value value="1"/>
   <Value value="2"/>
   <Value value="3"/>
  </DataField>
  <DataField name="accelerator_pedal_position" optype="continuous" dataType="double"/>
  <DataField name="engine_speed_Trns" optype="continuous" dataType="double"/>
  <DataField name="fuel_consumed" optype="continuous" dataType="double"/>
  <DataField name="fuel_level" optype="continuous" dataType="double"/>
  <DataField name="torque_at_transmission" optype="continuous" dataType="double"/>
  <DataField name="vehicle_speed" optype="continuous" dataType="double"/>
 </DataDictionary>

output file: We are getting output(Predicted_Cluster) as 1->1 and for 2->3 and 3->2.

Please suggest on the above mention.

**Comment by vruusmann** [comment]
I think that I have provided ample proof that JPMML-Evaluator is not broken when it comes to handling R generated SVM classification models.

If you still make a claim that the JPMML-Evaluator is broken, then it is your responsibility to prove it with a reproducible test case. I have not seen such proof so far.

This is not a place for getting free help about R programming basics.
