### ISSUE TITLE
Getting exception for clustering  

### ISSUE THREAD

**Issue by kltr8** [jpmml/jpmml-evaluator#23]
Hi,
I am new to clustering pmml model execution using jpmml evaluator.
Getting exception when I am running below line.

java -cp target/example-1.2-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model D:\analytics\Test\pmml\AuditKMeans.pmml --input D:\analytics\Test\csv\AuditData_Test.csv--output D:\analytics\Test\output\Audit_KmeansRes.csv

Exception in thread "main" java.lang.IllegalArgumentException: Missing active field(s): [Age, Income, Deductions, Hours]
        at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:217)
        at org.jpmml.evaluator.Example.execute(E
[Sample.zip](https://github.com/selvinsource/spark-pmml-exporter-validator/files/179556/Sample.zip)
xample.java:60)
        at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:127)

I have attached input and model files. 
[Sample.zip](https://github.com/jpmml/jpmml-evaluator/files/179557/Sample.zip)

Please help to sort out of the above exception.

**Comment by vruusmann** [comment]
You need to remove quotation marks from around input column (aka active field) names. For example, replace `"Age"` with `Age`.

Anyway, I would appreciate if you stopped spamming this project with off-topic issues.

This is not a place for getting help with basic programming questions (such as how CSV files should be formatted). Please consider posting them to StackOverflow, or some other general-purpose Q&A site like that.
