### ISSUE TITLE
pmml-evaluator-example dependency

### ISSUE THREAD

**Issue by ShalvaBagaturia** [jpmml/jpmml-evaluator#230]
Hi!
i gor the following error:
[ERROR] Failed to execute goal on project pmml-evaluator-example: Could not resolve dependencies for project org.jpmml:pmml-evaluator-example:jar:1.6-SNAPSHOT: org.jpmml:pmml-evaluator-testing:jar:1.6-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced 

any advice on fix this?

**Comment by vruusmann** [comment]
> org.jpmml:pmml-evaluator-testing:jar:1.6-SNAPSHOT was not 
> found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt.

I don't publish any snapshot versions anywhere. Why is your Apache Maven looking for them in the first place?

> any advice on fix this?

Are you getting this error when doing a git checkout, plus `mvn clean install`? This should always work, as demonstrated by GitHub Actions CI here:
https://github.com/jpmml/jpmml-evaluator/actions
https://github.com/jpmml/jpmml-evaluator/actions/runs/1272307763

The latest CI run was a git checkout and full build with JDK 8 through 14. All successful.

If you're looking for example command-line applications, then they are pre-built releases available here:
https://github.com/jpmml/jpmml-evaluator/releases

**Comment by ShalvaBagaturia** [comment]
Thanks
