### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Image;

### ISSUE THREAD

**Issue by zhang0557kui** [jpmml/jpmml-evaluator#236]
when I use:
```java
Evaluator evaluator = new LoadingModelEvaluatorBuilder()
  .load(new File("clf.pmml"))
  .build();
```
and this error occured:
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Image;

who can help me!

**Comment by vruusmann** [comment]
> java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Image;

The JPMML-Evaluator does not have any graphical components, and therefore does not import any classes from `java.awt.*` or `javax.swing.*` packages.

Therefore, this NoClassDefFoundError cannot be raised by the JPMML-Evaluator library, and should not be reported here.

> who can help me!

You can help yourself. Look at the error stack trace, and identify the correct problematic component/library/framework.
