### ISSUE TITLE
If the version 1.6.4 could work on java 8?

### ISSUE THREAD

**Issue by xiaoqiang95a** [jpmml/jpmml-evaluator#262]
I use Java8，but class org.jpmml.model.PMMLUtil import import jakarta.xml.bind.JAXBException;
how could java8 use the newest version 1.6.4 ?

**Comment by vruusmann** [comment]
> I use Java8，but class org.jpmml.model.PMMLUtil import import jakarta.xml.bind.JAXBException;

Fix your classpath!

Specifically, you need to include the `org.jpmml:pmml-evaluator-metro:1.6.4` dependency, as pointed out in the README file: https://github.com/jpmml/jpmml-evaluator#installation

Also, see the pinned issue: https://github.com/jpmml/jpmml-evaluator/issues/246
