### ISSUE TITLE
ModelEvaluator error

### ISSUE THREAD

**Issue by Alexkevin** [jpmml/jpmml-evaluator#31]
When running the following code 
`        ModelEvaluator<RegressionModel>  modelEvaluator = new RegressionModelEvaluator(model);
        Evaluator evaluator = (Evaluator) modelEvaluator;`

I got error like this :
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.from(Lcom/google/common/cache/CacheBuilderSpec;)Lcom/google/common/cache/CacheBuilder;

**Comment by vruusmann** [comment]
Your application classpath contains an outdated Google Guava library (`com.google.guava:guava`). Please update it to version 14.0 or newer (19.0 is recommended).

**Comment by Alexkevin** [comment]
@vruusmann many thanks
It wroks ~
