### ISSUE TITLE
jpmml is not a member of package org

### ISSUE THREAD

**Issue by ducminhgd** [jpmml/jpmml-evaluator#40]
I'm using Scala and SBT. In my `build.sbt`, I added this line:

```libraryDependencies += "org.jpmml" % "jpmml-evaluator" % "1.3.3"```

But I still got error *jpmml is not a member of package org* when importing.

For more information: Scala version is 2.11.8

**Comment by vruusmann** [comment]
You would need to "import" artifactId `pmml-evaluator` (not `jpmml-evaluator`).
