### ISSUE TITLE
Openscoring not supporting ensemble.GradientBoostingClassifier

### ISSUE THREAD

**Issue by MatiasSanchezCabrera** [jpmml/jpmml-evaluator#50]
Hello Vilu,

I've trained a ensemble.GradientBoostingClassifier classifier and deployed it to openscoring but I keep getting 400 after the requests. 

Using the same pipeline to generate the pmml (using sklearn2pmml) and requesting with the same input works well on simplier models (like linear_model.LogisticRegression()).

Is GradientBoostingClassifier supported by the sklearn2pmml but not by openscoring?

Thanks!

**Comment by vruusmann** [comment]
> Is GradientBoostingClassifier supported by the sklearn2pmml but not by openscoring?

The sklearn2pmml package depends on the JPMML-SkLearn library for the actual conversion functionality. All models types that are supported by sklearn2pmml/JPMML-SkLearn are covered by integration tests:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py

Specifically, the test resources for `GradientBoostingClassifier` are created here (binary and multi-class classification):
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L147
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L230

During JPMML-SkLearn project build, these test resources are executed using the latest JPMML-Evaluator library version, and the equality of Scikit-Learn and PMML predictions is asserted:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/java/org/jpmml/sklearn/ClassifierTest.java#L53
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/java/org/jpmml/sklearn/ClassifierTest.java#L136

So, you don't have to take my word for its correctness, you can actually verify it yourself!

> I've trained a ensemble.GradientBoostingClassifier classifier and deployed it to openscoring but I keep getting 400 after the requests.

You should really look into Openscoring log file.
