### ISSUE TITLE
Error: Could not find or load main class org.jpmml.evaluator.EvaluationExample

### ISSUE THREAD

**Issue by LeZhengThu** [jpmml/jpmml-evaluator#58]
Hi, I downloaded the jpmml-evaluator package and built it. Then I was following the example code: 
```
java -cp target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model xgb_r2pmml.pmml --input input.csv --output output.csv
```

But it threw out an error saying: 
```
Error: Could not find or load main class org.jpmml.evaluator.EvaluationExample. 
```
Does anyone knows why this happen and how to get it right? Thanks. I'm new to java and want to evaluate my pmml model converted from xgboost model trained in R.

**Comment by vruusmann** [comment]
Your working directory is incorrect. You're currently located in the root directory of the project (`jpmml-evaluator/`), but you should be located in its `pmml-evaluator-example` subdirectory (`jpmml-evaluator/pmml-evaluator-example/`):
```
$ cd pmml-evaluator-example
$ java -cp target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --help
```

Alternatively, you may prepend this path fragment to the example application JAR file:
```
$ java -cp pmml-evaluator-example/target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --help
```

Well, this issue looks like a Java/JVM usability bug. It should compalin about a missing JAR file (eg. "Could not find target/example-1.3-SNAPSHOT.jar"), and not about a missing Java application class (eg. "Could not find main class org.jpmml.evaluator.EvaluationExample").
