### ISSUE TITLE
TypeUtil.getDataType(Object value) does not recognize BigDecimal

### ISSUE THREAD

**Issue by johnellliott** [jpmml/jpmml-evaluator#6]
An exception is thrown when you pass a BigDecimal  into the ModelEvaluator method `prepare(activeField, rawValue)`. This is because `TypeUtil.getDataType(Object value)` does not check for BigDecimal values and an EvaluationException is thrown.

BigDecimal values are recognized as superior to Doubles/Floats for financial calculations and considered 'best practice'. It is recommended that the JPMML framework handles them without having to convert to a Double first.

Adding the following to the `getDataType(Object value)` method should resolve this issue:

`if(value instanceof BigDecimal){`
`   return DataType.DOUBLE;`
`} else`

*In addition: improving the message provided within the EvaluationException would also help with diagnosis of future issues. For example, the message 'the class java.math.BigDecimal is not a supported type' would improve the usability of the framework.*

**Comment by vruusmann** [comment]
The general contract of the `Evaluator` interface is that argument and result types are limited to `java.lang.String` and numeric Java primitive wrapper classes (ie. `Byte`, `Short`, `Integer`, `Long`, `Float` and `Double`).

The trouble with `java.math.BigInteger` and `java.math.BigDecimal` is that they are arbitrary-precision numerical data types. If you convert them to Java primitives (eg. using methods `#longValue()`, `#doubleValue()` etc.) then you are bound to lose precision. So, in my opinion, it is far better if such conversion operations are implemented transparently in the application code, not opaquely in the JPMML-Evaluator library code.

In your application code, you could adopt the following idiom:
```
Object userValue = ...;
Object preparedValue;
if(userValue instanceof java.lang.Number){
  Number userNumber = (Number)userValue;
  preparedValue = evaluator.prepare(activeField, userNumber.doubleValue());
} else {
  preparedValue = evaluator.prepare(activeField, userValue);
}
```

**Comment by johnelliott-** [comment]
I agree about your point regarding transparency.

However, why is a conversion to Double required at all? Perhaps the BigDecimal.toPlainString() method can provide a String value that will satisfy the Evaluator interface and will maintain precision. 

Whilst this has limited functional impact on my specific use, I am using BigDecimals all across my application and it would be nice to avoid having to convert to a double, then back again to BigDecimal. I can live with this limitation though.

As an aside, the loss of precision may have a larger impact on some financial applications of the framework, which typically have strict rules for handling precision.

BTW many thanks for your work on this framework. It's really excellent.

**Comment by vruusmann** [comment]
The JPMML-Evaluator library performs all numerical operations using `double` values. Perhaps it would be technically possible to introduce some kind of pluggable math abstraction layer that would let the application developer to switch over to `BigDecimal` API instead.

However, I'm afraid that this arbitrary-precision implementation would be dramatically slower. Therefore, you are better off using the existing implementation, and guarding its "entry" (ie. `BigDecimal` -> `double`) and "exit" points (`double` -> `BigDecimal`) manually in your application code.

You can "enrich" the model schema with precision information using extension elements (http://www.dmg.org/v4-2-1/GeneralStructure.html, scroll down to "Extension Mechanism"):
```
<DataField name="predictedPrice" dataType="double" optype="continuous">
  <Extension name="precision" value="8"/>
  <Extension name="roundingMode" value="HALF_UP"/>
</DataField>
```
You can use these Extension elements to construct an appropriate `java.math.MathContext` instance, that you can then use to construct an appropriate `BigDecimal` instance from the result `double` value. If I'm not mistaken then IBM SPSS has defined a (proprietary-) set of Extension elements exactly for this purpose.
