### ISSUE TITLE
Serialization help

### ISSUE THREAD

**Issue by marianatuma** [jpmml/jpmml-evaluator#69]
Hi everyone,

I'm trying to implement the serialization of results, but I don't have a lot of experience actually using this library, so I'm posting to ask what classes would be useful to have a toJson() method.

Here's what I have so far:

TargetField:
-"name" : getName()
-"dataType" : getDataType()
-"opType" : getOpType()
-"isSynthetic" : isSynthetic()

OutputField:
-"name" : getName()
-"dataType": getDataType()
-"opType" : getOpType()
-"isFinalResult" : isFinalResult()
-"depth" : getDepth()

Any suggestions of what else would be useful to have in Json form?

EDIT: the children of Computable (Association, Classification, ReasonCodeRanking and NodeScore) also seem to need to be serializable

**Comment by vruusmann** [comment]
No need to over-engineer - only send these parts of model schema that the client application actually can understand and use.

For example, when the client application is reading input from CSV files, and writing results to CSV files, then it only needs to know field names (as columns in the CSV file are mapped to PMML fields by name, not by position) - `org.jpmml.evaluator.InputField#getName()` and `org.jpmml.evaluator.ResultField#getName()`.
