### ISSUE TITLE
Apply with invalidValueTreatment="asMissing"

### ISSUE THREAD

**Issue by infiton** [jpmml/jpmml-evaluator#70]
I am trying to use the `Apply#invalidValueTreatment` attribute to concisely create a z-score transformed field: here is some minimal PMML:

```xml
<PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3">
  <DataDictionary numberOfFields="4">
    <DataField name="x1" optype="continuous" dataType="double"/>
    <DataField name="x2" optype="continuous" dataType="double"/>
    <DataField name="x3" optype="continuous" dataType="double"/>
    <DataField name="y" optype="continuous" dataType="double"/>
  </DataDictionary>
  <TransformationDictionary>
    <DerivedField dataType="double" name="z_score" optype="continuous">
      <Apply function="/" invalidValueTreatment="asMissing" mapMissingTo="0">
         <Apply function="-">
            <FieldRef field="x1" />
            <FieldRef field="x2" />
         </Apply>
         <FieldRef field="x3" />
      </Apply>
    </DerivedField>
  </TransformationDictionary>
  <RegressionModel modelName="LR" functionName="regression">
    <MiningSchema>
      <MiningField name="x1" missingValueReplacement="0" usageType="active"/>
      <MiningField name="x2" missingValueReplacement="0" usageType="active"/>
      <MiningField name="x3" missingValueReplacement="0" usageType="active"/>
      <MiningField name="y" usageType="target"/>
    </MiningSchema>
    <RegressionTable intercept="0.5" targetCategory="no">
      <NumericPredictor name="z_score" coefficient="-1.5"/>
    </RegressionTable>
  </RegressionModel>
</PMML>
```

when the input for `x3` is either `0` or `missing` I want the zscore to be `0`. Running this with the following csv

```
x1,x2,x3
1,1,0
1,1,
```

gives me `y = NaN` for both. From http://dmg.org/pmml/v4-3/Functions.html#xsdElement_Apply:

> The application of a function may sometimes yield invalid results (e.g. a division by zero). As in the case of a MiningField, the attribute invalidValueTreatment can be used to specify how such invalid values should be treated. This attribute’s default value returnInvalid causes the model to return a value indicating an invalid result. On the other hand, the invalidValueTreatment value asMissing replaces the invalid value with a missing value. 

Am I using the element wrong or is this an issue with `jpmml`?

**Comment by vruusmann** [comment]
Without consulting with the PMML specification or JPMML-Evaluator source code, here's my interpretation:

- The `Apply@mapMissingTo` attribute applies to **_incoming_** values. If the result of subtraction `x1 - x2` was missing (eg. could happen if one of the operands were missing), or the denominator `x3` was missing, then `0` would be returned without actually evaluating the `Apply` element.
- The `Apply@invalidValueTreatment` attribute applies to the **_outgoing_** (aka result) value. The primary use case is "downgrading" a DivisionByZeroException to a mere missing value.

You could attain the desired behaviour by wrapping the existing `Apply` element into another one:
```XML
<Apply function="if">
  <Apply function="isNotMissing"/>
    <FieldRef field="potentiallyMissingField"/>
  </Apply>
  <!-- TRUE case -->
  <FieldRef field="potentiallyMissingField"/>
  <!-- FALSE case -->
  <Constant>0</Constant>
</Apply>
```

**Comment by vruusmann** [comment]
The above interpretation appears to be correct.

However, there's the `Apply@defaultValue` attribute, which applies to the **_outgoing_** value. You should be able to map your use case to:
```XML
<Apply invalidValueTreatment="asMissing" defaultValue="0">
  <!-- Some function that may return an invalid value -->
</Apply>
```

The JPMML-Evaluator doesn't seem to handle this sequence correctly, because the method `ExpressionUtil#evaluateApply(Apply, EvaluationContext)` returns "early".

**Comment by infiton** [comment]
yah I meant this transformation:

```
<Apply function="/" invalidValueTreatment="asMissing" defaultValue="0">
   <Apply function="-">
      <FieldRef field="x1" />
      <FieldRef field="x2" />
   </Apply>
   <FieldRef field="x3" />
</Apply>
```

but I do get `NaN`, so I think that needs a fix in JPMML-Evaluator

**Comment by vruusmann** [comment]
> but I do get NaN, so I think that needs a fix in JPMML-Evaluator

The `NaN` value is valid. So, the invalid value treatment logic is not triggered at all.

**Comment by infiton** [comment]
> yield invalid results (e.g. a division by zero)

division by zero should be invalid shouldn't it?

**Comment by vruusmann** [comment]
> division by zero should be invalid shouldn't it?

In Java, division by zero in "integer mode" throws an `ArithmeticException`, whereas division by zero in "double mode" returns `Infinity` or `NaN`.

Does that make `Infinity` and `NaN` invalid values? Please add your thoughts here: http://mantis.dmg.org/view.php?id=168

**Comment by infiton** [comment]
ok thanks! looks like this is unspecified behaviour in PMML

**Comment by vruusmann** [comment]
Reopening, because the sequence `Apply@invalidValueTreatment="asMissing"` plus `Apply@defaultValue` is not correctly handled in JPMML-Evaluator.

**Comment by vruusmann** [comment]
Double-checked the code, the conversion of invalid results to missing results to default value is handled correctly in the `ExpressionUtil#evaluateApply(Apply, EvaluationContext)` method:
https://github.com/jpmml/jpmml-evaluator/blob/1.3.9/pmml-evaluator/src/main/java/org/jpmml/evaluator/ExpressionUtil.java#L439-L466

The "early" return (on line 455) executes exactly the same code as the "final" return (on line 463).
