### ISSUE TITLE
jpmml-evaluator for XGBoost

### ISSUE THREAD

**Issue by dotzip** [jpmml/jpmml-evaluator#76]
Good day! I want ask you for help.  I have a successful result with jpmml-evaluator in Random Forest. But, when i wanted to evaluate a pmml file with xgboost model - i have got a failure. 
Have you got an example with evaluate a XGBoost model? 

Exception while executing a program:
```
Exception in thread "main" org.jpmml.evaluator.MissingValueException: PredictedField
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:143)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:200)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:167)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:162)
```

**Comment by vruusmann** [comment]
Exception type `org.jpmml.evaluator.MissingValueException` means that the `Output` element of your XGBoost model contains an "unsatisfied" reference to a field `PredictedField`.

The most probable cause for this exception is that your XGBoost model has been incorrectly translated to PMML. Let me guess, you were using R's standard [`pmml`](https://cran.r-project.org/web/packages/pmml/index.html) package for the job? Please switch to some proper converter such as the [`r2pmml`](https://github.com/jpmml/r2pmml) package instead.

Incidentally, I posted some relevant information to the JPMML mailing list earlier today:
https://groups.google.com/d/msg/jpmml/k6eWMXp8kAQ/xmfmb5wbAQAJ

**Comment by vruusmann** [comment]
Closing this issue as invalid (the PMML document is broken, not the JPMML-Evaluator library).
