### ISSUE TITLE
About arctan activationFunction in PMML Neural Networks model

### ISSUE THREAD

**Issue by InformacionUtil** [jpmml/jpmml-evaluator#77]
In Neural Network model for arctan activationFunction your code just computes Math.atan() but in PMML standard (http://dmg.org/pmml/v4-3/NeuralNetwork.html) the formula is:
**arctan:**
_activation(Z) = 2 * arctan(Z)/Pi_

The reason for multiplying for 2/PI is to change the domain from (-π/2, π/2) to (-1, 1)

**Comment by vruusmann** [comment]
This appears like a legitimate bug.

How did you discover it? Is there some kind of PMML producer software available that can export NN models with `arctan` activation function?

**Comment by InformacionUtil** [comment]
We are working in an automatic random PMML generator. We feed the generated PMML files to PMML consumer programs and compare the results.

Thank you for solving this bug and for your job in this marvelous JPMML software.

**Comment by vruusmann** [comment]
> Thank you for solving this bug and for your job

The fix currently lives in the `master` branch of the repository. The updated JPMML-Evaluator library (that would be version 1.3.10) will be published over this weekend.

> We are working in an automatic random PMML generator.

Will you be sharing your work? I've also thought about building a similar thing (random data generator based on PMML/model data schema) as it has many application areas - next to testing the correctness of predictions, it would come in handy for demonstrating performance changes between JPMML-Evaluator library versions (eg. what's the average number of scores per seconds for different versions).

The data generator could have several operation modes - completely random vs. emulating the training dataset. For example, the SkLearn2PMML/JPMML-SkLearn converter stack is embedding feature distribution information into PMML documents, which could be used in the latter mode.

**Comment by InformacionUtil** [comment]
Our automatic random PMML generator is not yet stable. As a tentative date, we believe it will be stable this year in December.
We would not mind sharing it with you in that date.
