### ISSUE TITLE
About variable previousValue in GeneralRegressionModelEvaluator.java

### ISSUE THREAD

**Issue by InformacionUtil** [jpmml/jpmml-evaluator#78]
Dear Sir:

In commit whose hash starts with 1b1987f, date Aug 2, 2017 (“Refactored the evaluation of general regression models”), in file GeneralRegressionModelEvaluator.java, function evaluateClassification( ), you changed variable **previousValue**
Previously it was created as double with value 0d. Now is an object and is created with value null.
If modelType is ORDINAL_MULTINOMIAL you do:
_value.subtract(previousValue);_
In the first iteration of the for loop previousValue is still null, so it may throw an Exception.

Previous versions did not show this behavior.

**Comment by vruusmann** [comment]
Well spotted!
