### ISSUE TITLE
Pom error is coming while trying to build pmml-evaluator-example

### ISSUE THREAD

**Issue by pranayaptus** [jpmml/jpmml-evaluator#90]
Project build error: Non-resolvable parent POM for org.jpmml:pmml-evaluator-example:[unknown-version]: Failure to find 
 org.jpmml:jpmml-evaluator:pom:1.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local 
 repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced and 
 'parent.relativePath' points at wrong local POM

**Comment by vruusmann** [comment]
Fix your local environment and/or Apache Maven installation.

The JPMML-Evaluator project builds cleanly from the source checkout. The build produces a set of JAR files, including the `org.jpmml:pmml-evaluator-example:1.3-SNAPSHOT` executable JAR file.

See: https://travis-ci.org/jpmml/jpmml-evaluator
