### ISSUE TITLE
POM file error while trying to build 

### ISSUE THREAD

**Issue by pranayaptus** [jpmml/jpmml-evaluator#91]
Non-resolvable parent POM for org.jpmml:pmml-evaluator-example:[unknown-version]: Failure to find 
 org.jpmml:jpmml-evaluator:pom:1.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local 
 repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced and  'parent.relativePath' points at wrong local POM

**Comment by vruusmann** [comment]
Duplicate of #90 

Please fix your local environment and/or Apache Maven installation.
