### ISSUE TITLE
ScoreDistribution probability sanity check chokes on floating-point round-off error

### ISSUE THREAD

**Issue by rriegs** [jpmml/jpmml-evaluator#94]
The test at TreeModelEvaluator.java line 362,
https://github.com/jpmml/jpmml-evaluator/blob/7d41e4eb2fc23476bee535ae58a2d14768faa4da/pmml-evaluator/src/main/java/org/jpmml/evaluator/tree/TreeModelEvaluator.java#L362 checks whether given ScoreDistribution probabilities sum to exactly `1d`.  Given the imprecise nature of floating-point number representations, this is commonly not the case, even when the numbers' decimal representations _do_ sum to exactly 1.

Two possible solutions are as follows:

1. The easiest and computationally fastest solution is to permit a small deviation from zero in the final sum.  Double-precision floating-point numbers are accurate to about 15 decimal places while single-precision are accurate to about 6, so for a total that should equal about 1, testing `abs(1 -
 sum) < 1e-14` or `1e-5` for the respective types (or just `1e-5` for both) should suffice for all but the most pathological sums.

2. A more correct but considerably more challenging solution is to instead use BigDecimal when sanity checking the sum of probabilities read from the file.  This is not as easy as it sounds because, in order to do so, it is not possible to use `ScoreDistribution.getProbability()` to obtain the values to check: they will already have been converted to doubles by then, and BigDecimal is only useful here if it is initialized directly from the input strings.

Given the difficulty of the later solution, the former is almost certainly the way to go.

**Aside:** It might also be a good idea to ensure that each of the individual probabilities are themselves between 0 and 1.

**Comment by rriegs** [comment]
I note that a viable workaround is to avoid use of ScoreDistribution's probability attribute altogether and instead encode the information in recordCount.  It is always possible to set recordCount equal to the containing Node's recordCount times the ScoreDistribution's probability.  (Given that recordCount is a required attribute, this is likely what it is already set to.)

**Comment by vruusmann** [comment]
Related to #89

**Comment by vruusmann** [comment]
The suggestion to promote `ScoreDistribution@probability` attributes to `ScoreDistribution@recordCount` attributes could be again implemented as a Visitor class:
1. Load a `PMML` object from a PMML document.
2. `new ScoreDistributionProbabilityPromoter().applyTo(pmml); // TODO`
3. Save the `PMML` object to a PMML document.

I'm a bit surprised that this `sum.doubleValue() != 1d` sanity check is causing so much problem. Must be more acute with PMML documents that have been exported by non-Java software (eg. proprietary C(++) software). I haven't seen this sanity check triggered with any PMML document that has been generated/exported by JPMML-family of libraries (eg. JPMML-R, JPMML-SkLearn, JPMML-SparkML).
