### ISSUE TITLE
Warn if the model does not produce any visible results

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-evaluator#95]
Some PMML producer software generate model files that don't have any target or output field definitions. Such models execute, but don't produce any end user-accessible results.

See https://groups.google.com/d/topic/jpmml/kU-tJ5elMdE/discussion

**Comment by vruusmann** [comment]
Related to #44

**Comment by mariobriggs** [comment]
@vruusmann I was trying a similar 'no-op' model with the 'jpmml-evaluator-spark' and there in this situation, the 'transformation' does not add the 'java.util.Map' that is returned by Evaluator#evaluate(Map) in jpmml-evaluator, as a new column. Your thoughts on the 'transformation' adding it ?

**Comment by vruusmann** [comment]
> Your thoughts on the 'transformation' adding it?

I would argue that the PMML document is functionally invalid. What's the point of productionizing no-op models?

The PMML consumer should not attempt to "fix" such PMML documents. Instead, it should fail fast and very noticeably - the goal is to send the PMML document back to the data science team and have them fix it.

The "fail fast and very noticeably"-part is framework dependent. For example, in the JPMML-Evaluator-Spark library, the `TransformerBuilder#build()` method should throw `IllegalArgumentException("The PMML document does not produce any result columns")`.

Your perspective/thoughts?

**Comment by mariobriggs** [comment]
> Your perspective/thoughts?

Will get back after checking with the data science owners of these models

**Comment by vruusmann** [comment]
If you want to fix a no-op PMML document in deployment environment, then your devops engineers have  to "fix" each model individually. This would defeat the whole value proposition - five lines of standardized application code to handle models with "complete" schema _versus_ fifty lines of custom application code to handle models with "incomplete" schema.

A no-op PMML document cannot be fixed at the library level. For example, if the JPMML-Evaluator generates some synthetic target and output fields (in order to make an "incomplete" schema "complete"), then you would have no idea what those fields represent - the confusion is simply pushed down the chain (ie. the agent responsible for working with the Apache Spark dataframe after PMML model scoring stage will be having a bad day).

**Comment by suramao4** [comment]
Hmm, this definitely looks like a bug from my codes. I will look into it.
