### ISSUE TITLE
where is ProbabilityClassificationMap

### ISSUE THREAD

**Issue by greghines** [jpmml/jpmml-evaluator#98]
Hi - some older code I found online refers to ProbabilityClassificationMap (https://henning.kropponline.de/2015/09/06/jpmml-example-random-forest/) I can't find any such variable in the current code base. What has it been replaced with?

Cheers

**Comment by vruusmann** [comment]
It's year 2018 now, and the JPMML-Evaluator library has just graduated to 1.4.X development branch.

Class `ProbabilityClassificationMap` has probably been refactored to `org.jpmml.evaluator.ProbabilityDistribution`. It's a subclass of `org.jpmml.evaluator.Classification`, which implements interface `org.jpmml.evaluator.HasProbability`.

You should always develop your code against JPMML-Evaluator result feature interfaces (ie. subinterfaces of `org.jpmml.evaluator.ResultFeature`), not concrete classes. Interfaces are guaranteed to be stable and predictable, whereas individual classes come and go at will.

**Comment by greghines** [comment]
FYI I am well aware of the year, but that page is the top hit for me when I search "jpmml random forest". Maybe some documentation needs to be updated.
